"""Session AB: the fidelity receipt, and the live-generation defect it exposed.

    python3 docs/audits/fable5-vision-audit-20260725/phase6/receipts/ab_port_parity.py

WHAT IS BEING CHECKED
----------------------
`regime_spine.conditions` re-expresses each armed sleeve's rule as a gate chain so the
funnel can be attributed. Everything this session claims rests on that chain being the
production rule. The check is behavioural: compare its fire set against
`X_ESTATE_TRADES.json.gz`, which Session X generated by driving `GenerationPort` — the
production `UltimateBookLiveEngine._generate_intents` behind a bar feed.

WHAT IT FOUND, WHICH WAS NOT THE POINT
----------------------------------------
`only_port == 0` and `geometry_mismatches == 0` for all five H4 sleeves: this package
never misses a bar the live engine fires on, and never disagrees about direction or stop.

It fires on **29 bars the engine does not**, and all 29 sit immediately before a data gap
of two intervals or more. The mechanism, read off production:

  `bar_provider.candles_to_bars` (`:54-58`) drops the last candle **unconditionally**
  (`rows = candles[:-1]`). At a session close there is no forming bar, so the last candle
  IS the freshly-closed decision bar and it is discarded. By the time the next session's
  bar starts forming, that bar's close is more than two intervals old and
  `book_engine.py:512` (`if (now - bar_close).total_seconds() > 2 * ivl * 60: continue`)
  refuses it as stale.

So the last closed bar before every weekend and holiday is structurally unreachable by the
live book. On the armed surface that is 1.3 % to 6.8 % of each sleeve's fires — and the
sleeve it costs most, `sub_xvol_pullback` at 6.4 %, is the one whose gate failure is
significance at n=88.

`[MEASURED]` on the archive replay, which reproduces the convention exactly.
`[UNVERIFIED]` on the live MT5 feed: whether MT5 returns a forming bar at a session close
is a property of the terminal this session cannot reach. The fix
(`bar_provider.keep_closed_last`) is written and tested here and is inert until a caller
passes `now`; wiring it is one line and an owner decision, because it changes which bars
an armed book trades.
"""

from __future__ import annotations

import datetime as dt
import gzip
import json
import os
import pickle
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[5]
sys.path.insert(0, str(REPO))

from src.research_infra.regime_spine import conditions as C  # noqa: E402
from src.research_infra.regime_spine.archive import ARCHIVE, frames_for  # noqa: E402

HERE = Path(__file__).resolve().parent
ESTATE = (REPO / "docs/audits/fable5-vision-audit-20260725/phase5/receipts"
          / "X_ESTATE_TRADES.json.gz")
OUT = HERE / "AB_PORT_PARITY_V1.json"
FRAME_CACHE = os.environ.get("AB_FRAME_CACHE", "")

H4_SLEEVES = ("metals_core", "metals_softband", "energy_agri", "crypto",
              "sub_xvol_pullback")
IVL = dt.timedelta(hours=4)


def main() -> dict:
    t0 = time.time()
    est = json.load(gzip.open(ESTATE, "rt"))
    want = sorted({s for n in H4_SLEEVES for s in C.SLEEVES[n].surface})
    cache: dict = {}
    if FRAME_CACHE and Path(FRAME_CACHE).is_file():
        cache = pickle.load(open(FRAME_CACHE, "rb"))
    frames = frames_for(want, 16388, cache=cache)

    out = {
        "schema": "gtos.wave6.regime_spine.port_parity.v1",
        "generated_by": str(Path(__file__).relative_to(REPO)),
        "bars_archive": ARCHIVE,
        "compared_against": str(ESTATE.relative_to(REPO)),
        "compared_against_generator": est.get("generated_by"),
        "sleeves": {},
    }
    total_extra = total_pregap = 0
    for name in H4_SLEEVES:
        cond = C.SLEEVES[name]
        ours, geo = set(), {}
        for canon in cond.surface:
            f = frames.get(canon)
            if f is None:
                continue
            for i, intent in C.fires(f, cond):
                key = (f.symbol, f.times_utc[i].isoformat())
                nxt = (f.times_utc[i + 1] - f.times_utc[i]) if i + 1 < len(f) else None
                ours.add(key)
                geo[key] = (intent, nxt)
        port = {(r["symbol"], r["decision_bar_iso"])
                for r in est["trades"].get(name, [])}
        only_ours = ours - port
        pre_gap = [k for k in only_ours
                   if geo[k][1] is not None and geo[k][1] > IVL]
        mism = 0
        for r in est["trades"].get(name, []):
            k = (r["symbol"], r["decision_bar_iso"])
            if k not in geo:
                continue
            intent, _ = geo[k]
            if (intent["direction"] != r["direction"]
                    or abs(intent["stop_dist"] - r["sl_distance_price"]) > 1e-12):
                mism += 1
        out["sleeves"][name] = {
            "n_ours": len(ours), "n_port": len(port),
            "only_port": len(port - ours),
            "only_ours": len(only_ours),
            "only_ours_pre_gap": len(pre_gap),
            "only_ours_pct_of_ours": (round(100 * len(only_ours) / len(ours), 3)
                                      if ours else None),
            "geometry_mismatches": mism,
            "pre_gap_examples": sorted(
                [{"symbol": k[0], "decision_bar": k[1],
                  "next_bar_gap_intervals": geo[k][1] / IVL} for k in pre_gap],
                key=lambda d: d["decision_bar"])[:6],
        }
        total_extra += len(only_ours)
        total_pregap += len(pre_gap)
        r = out["sleeves"][name]
        print(f"{name:20s} ours={r['n_ours']:5d} port={r['n_port']:5d} "
              f"only_port={r['only_port']:3d} only_ours={r['only_ours']:3d} "
              f"(pre-gap {r['only_ours_pre_gap']}) geom_mismatch={mism} "
              f"= {r['only_ours_pct_of_ours']}% of fires")

    out["totals"] = {
        "extra_fires": total_extra,
        "extra_fires_pre_gap": total_pregap,
        "all_extra_are_pre_gap": total_extra == total_pregap,
    }
    out["mechanism"] = {
        "where": ["src/components/ultimate_book/bar_provider.py:54-58",
                  "src/components/ultimate_book/book_engine.py:512"],
        "what": ("`candles_to_bars` drops the last candle unconditionally. At a session "
                 "close the last candle is the freshly-closed decision bar, so it is "
                 "discarded; by the next session its close is > 2 intervals old and the "
                 "recency guard refuses it. The last closed bar before every gap is "
                 "unreachable."),
        "evidence_class_archive": "[MEASURED] — the replay reproduces the convention exactly",
        "evidence_class_live": ("[UNVERIFIED] — whether the live MT5 terminal returns a "
                                "forming bar at a session close cannot be checked from "
                                "this machine"),
        "fix": ("bar_provider.candles_to_bars(..., now=<clock>) keeps a last candle that "
                "is provably closed. Written and tested; inert unless a caller passes "
                "`now`, so nothing changes until someone wires it."),
        "wiring": ("book_engine.get_closed_bars(..., now=now, interval_minutes=ivl) at "
                   "the single call site — one line. It changes which bars an armed book "
                   "trades, so it is an owner decision, not a session's."),
    }
    OUT.write_text(json.dumps(out, indent=1, sort_keys=True, default=str) + "\n")
    print(f"\n{total_extra} extra fires, {total_pregap} of them pre-gap "
          f"({'all' if total_extra == total_pregap else 'NOT ALL'})")
    print(f"wrote {OUT.relative_to(REPO)} in {time.time()-t0:.1f}s")
    return out


if __name__ == "__main__":
    main()
