import json,os,statistics as st
D='/Users/borr/GTOSActive/worktrees/wave19-broad-forensic-20260801/docs/audits/fable5-vision-audit-20260725/phase19/receipts/discovery'
R=json.load(open(f'{D}/e2_RESULT.json'))
MO=['JAN','FEB','MAR','APR','MAY']
o=[]
A=o.append
A("# e2_RESULT — EXTENSION of l10-broker-truth X7 (the honest cost ledger) to FIVE months\n")
A("Lane **e2**. Posture: extension, not refutation. Wave 19 broad forensic swarm.\n")
A("Every number below is measured; every script is in `e2_scripts/` beside this file.\n")
A("**Evidence class: DISCOVERY / lane iteration, `billed:false`. No admission claim.**\n")
A("\n---\n\n## 0. TL;DR\n")
A("1. **The finding reproduces EXACTLY.** 60/60 book fields to 1e-6, twice — once through the original")
A("   working-set input and once through an independently rebuilt portable instrument reading the raw pool.")
A("   `+0.473864 R/trade` is confirmed.\n")
A("2. **It HOLDS in every month it was not found on.** February, March, April and May all show the same")
A("   structure: the frozen cost model overcharges by **3.13x–3.50x**, worth **+0.2798 to +0.4739 R/trade**,")
A("   and **all 25 month x book cells stay negative**. The gross deficit is binding in every month.\n")
A("3. **NEW — the frozen cost model is a RANKING error, not a scale error.** Row-level Spearman between")
A("   frozen and real total cost is only **0.371–0.598**, and the frozen gate and a real-cost gate")
A("   **disagree on 34.9%–44.7% of every month's pool**. Correcting cost does not merely re-price the same")
A("   book — it changes *which* candidates are admitted, on more than a third of the pool. Per-symbol the")
A("   frozen/real ratio spreads **50x–152x**.\n")
A("4. **NEW — the 12.1x family dispersion is priced, and it travels.** The family real-cost ordering is")
A("   near-invariant across four months (**mean Spearman 0.9818**). Selecting the 4 cheapest families and 12")
A("   cheapest symbols *on January only*, plus a real-cost gate, moves net@real from **-0.4068 to -0.1231**")
A("   in January and **-0.4396 to -0.1216** in May — **mean +0.282 R/trade across five months**, at")
A("   ~2,400-3,300 rows/month. Still negative everywhere.\n")
A("5. **NEW — the estate's best conditioned cell.** `{regime_transition_break, volatility_compression_expansion}")
A("   x NY session`, takeable, is **gross-positive in 3 of 5 months** and is the only cell of 100 declared")
A("   with a positive five-month mean **net**@real (+0.0036 pooled). Pooled gross +0.0331, bootstrap 90% CI")
A("   **[-0.0195, +0.0870]**, permutation p **0.0548** vs same-month NY peers, **n=390** total. Discovery-grade.\n")
A("6. **BOUNDARY / localization.** l10's per-symbol claims are JANUARY-ONLY. `USDCHF +0.0117` becomes")
A("   -0.2373 / -0.1337 / -0.1169 / -0.0505 in the other four months (mean **-0.1053**); `GER40 -0.0030`")
A("   becomes mean **-0.1204**. **No symbol of 24 has positive mean gross over five months.** The SESSION")
A("   axis replaces it: `london` mean gross **-0.0251** (n=18,538), `ny` **-0.0694** (n=18,247), against")
A("   -0.115 to -0.137 for every hour bucket outside them.\n")
A("\n---\n\n## 1. Reproduction — the instrument matches\n")
r=R['REPRODUCTION']
A(f"| check | value |\n|---|---|\n| book-field checks run | {r['checks']} |\n| failures | **{r['failures']}** |")
A(f"| target headline (`L10X_BOTTOMLINE_V1.json`) | {r['headline_target']} |")
A(f"| reproduced via original working-set input | {r['headline_reproduced_via_workingset']} |")
A(f"| reproduced via portable raw-pool instrument | {r['headline_reproduced_via_raw_pool_portable_instrument']} |\n")
A(f"**{r['verdict']}**\n")
A("Both paths were checked on all five books (A/B/C/D/E) x six fields (n, gross, frozen_cost, real_cost,")
A("net_frozen, net_real). The portable path recomputes `risk_distance = |entry_price - stop_loss|` and")
A("`gross_r = opportunity_net_proxy_r + cost_r` from the raw pool rather than reading the working set, so it")
A("proves the instrument is transportable, which is what the rest of this lane depends on.")
A("Script: `e2_scripts/e2_01_repro_jan.py` -> `E2_JAN_REPRO_V1.json`.\n")
A("**One deliberate difference, declared.** The original January anchor")
A("(`w0cap2_DECISION_ANCHOR_V1.jsonl.gz`) loaded only `bridge_ftmo_m1_202601`, so 17 rows near the month")
A("boundary were unanchored and `born_past_stop` was 3,516. The portable anchor also loads the prior month,")
A("anchors **27,658/27,658**, and finds **3,519**. The takeable book moves 24,142 -> 24,139 and net@real")
A("-0.291914 -> -0.291930. The exact reproduction above uses the ORIGINAL anchor; every cross-month table")
A("uses the portable one, for comparability.\n")
A("\n---\n\n## 2. THE EXTENSION — five months, one instrument\n")
A("Cost model is identical in every month by construction: per-symbol median spread in bps from the FTMO")
A("tick archive (2026-06-18..07-24), measured broker commission, measured live slippage, swap 0 at the 2 h")
A("horizon. It is **month-invariant**, so every month-to-month change below comes from row GEOMETRY")
A("(entry price / risk distance mix), never from a spread that moved.\n")
A("### 2.1 Book A — all rows\n")
A("| month | n | gross | frozen cost | real cost | net @ frozen | net @ real | **WORTH of the correction** | ratio |")
A("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
for m in MO:
    v=R['MONTHS'][m]
    A(f"| {m} | {v['n']:,} | {v['gross']:.4f} | {v['frozen_cost']:.4f} | {v['real_cost']:.4f} | {v['net_frozen']:.4f} | {v['net_real']:.4f} | **+{v['WORTH_OF_COST_CORRECTION']:.4f}** | {v['overcharge_ratio']:.2f}x |")
s=R['MONTH_SUMMARY']
A(f"\n**Range +{s['worth_min']} to +{s['worth_max']}, mean +{s['worth_mean']}. Overcharge ratio {s['ratio_min']}x-{s['ratio_max']}x.**")
A("January is the LARGEST of the five, so the published +0.473864 is the top of the range, not the centre.\n")
A("**March is the strongest corroboration in the set.** Its R0 arm was run with")
A("`commission_broker_true_gated` and `swap_horizon_true` already applied")
A("(`FA2_M_R0_RECEIPT.json` -> `patches_applied`), so its frozen cost is already partly repaired:")
A("0.4046 vs January's 0.6632. **The overcharge ratio barely moves — 3.24x vs 3.50x.** Repairing")
A("commission and swap in the engine left the ratio essentially where it was, because the residual is")
A("the SPREAD term, exactly as `w0-dictionary` D1 predicted (spread is 85.08% of frozen cost and is the")
A("term measured overcharged 7.3-8.5x).\n")
A("### 2.2 Real cost decomposition (R/trade, all rows)\n")
A("| month | spread | commission | slippage | total |\n|---|---:|---:|---:|---:|")
for m in MO:
    d=R['MONTHS'][m]['real_cost_decomp']
    A(f"| {m} | {d['spread']:.4f} | {d['commission']:.4f} | {d['slippage']:.4f} | {R['MONTHS'][m]['real_cost']:.4f} |")
A("\n### 2.3 The full ladder — every cell negative in every month\n")
A("| month | B takeable | C frozen gate | D real gate | E cheapest half | born_past_stop share |")
A("|---|---|---|---|---|---:|")
for m in MO:
    v=R['MONTHS'][m]['books']
    A(f"| {m} | {v['B_takeable_only']['net_real']:.4f} (n={v['B_takeable_only']['n']:,}) | {v['C_takeable_at_frozen_gate']['net_real']:.4f} (n={v['C_takeable_at_frozen_gate']['n']:,}) | {v['D_takeable_at_real_gate']['net_real']:.4f} (n={v['D_takeable_at_real_gate']['n']:,}) | {v['E_takeable_real_gate_cheapest_half']['net_real']:.4f} (n={v['E_takeable_real_gate_cheapest_half']['n']:,}) | {100*R['MONTHS'][m]['born_past_stop_share']:.2f}% |")
A("\n**25 of 25 month x book cells are negative.** l10's central claim — *the gross deficit, not cost, is")
A("binding* — holds out of window without a single exception.\n")
A("One ordering exception worth naming: in **April the E book (-0.1655) is WORSE than the C book (-0.1748)**")
A("... in fact April is the one month where the real-cost gate does not beat the frozen gate")
A(f"(D {R['MONTHS']['APR']['books']['D_takeable_at_real_gate']['net_real']:.4f} vs C {R['MONTHS']['APR']['books']['C_takeable_at_frozen_gate']['net_real']:.4f}).")
A("In April, cheaper cohorts have *worse* gross. That is the single clearest boundary in this lane.\n")
open(f'{D}/e2_RESULT_part1.md','w').write("\n".join(o))
print('part1 lines',len(o))
