#!/usr/bin/env python3
"""Independently verify one sealed post-acceleration arm without reading economics.

The verifier authenticates the producer receipt, frozen decision contract,
execution seal, prepared-pack authority, artifact names, exact logical bytes,
SHA-256 digests, and JSONL row counts.  JSONL is scanned as opaque bytes and
line framing; economic JSON objects are never decoded or emitted.  The same
verification works before or after the three large ledgers are cold-demoted.

Since 2026-07-26 it also requires an arm-bound **divergence matrix**
(`--divergence-matrix`, generated by `src/research_infra/divergence_matrix.py`).
`CLAUDE.md` H7 — "replay does not measure the live system; do not transfer replay R
to a production claim without the divergence matrix" — used to depend on somebody
remembering it.  It is now a required input, and the matrix's `transfer_verdict`
lands in the verification receipt beside the arm's identity, so no accepted arm can
exist without a statement of how far its numbers are from live ones.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any, Mapping
import uuid

from compression import zstd


ROUTE_DIR = Path(__file__).resolve().parent
REPO_ROOT = ROUTE_DIR.parents[2]
if str(ROUTE_DIR) not in sys.path:
    sys.path.insert(0, str(ROUTE_DIR))
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from b7_5_cold_evidence import ColdEvidenceError, RawOrColdResolver  # noqa: E402
from src.research_infra.divergence_matrix import (  # noqa: E402
    DivergenceMatrixError,
    SCHEMA as DIVERGENCE_MATRIX_SCHEMA,
    verify_matrix as verify_divergence_matrix,
)


SCHEMA = "gtos.b7_5.post_acceleration_arm_independent_verification.v1"
PASS_STATUS = "PASS_POST_ACCELERATION_ARM_ARTIFACTS_INDEPENDENTLY_VERIFIED"
RECEIPT_SCHEMA = "gtos.b7_5.post_acceleration_arm_execution.v1"
RECEIPT_STATUS = "POST_ACCELERATION_ARM_EXECUTION_COMPLETE"
DECISION_SCHEMA = "gtos.b7_5.post_acceleration_decision_contract.v1"
DECISION_STATUS = (
    "SEALED_POST_ACCELERATION_REPLAY_FREE_DECISION_CONTRACT_VALID"
)
EXECUTION_SCHEMA = "gtos.b7_5.post_acceleration_execution_seal.v1"
EXECUTION_STATUS = "SEALED_POST_ACCELERATION_EXECUTION_CONTRACT_VALID"
PACK_AUTHORITY_SCHEMA = (
    "gtos.b7_5.post_acceleration_prepared_pack_rebind_authority.v2"
)
PACK_AUTHORITY_STATUS = (
    "POST_ACCELERATION_PREPARED_PACK_REBOUND_TO_CURRENT_CONTRACT"
)
SOURCE_AUTHORITY_SCHEMA = (
    "gtos.replay_acceleration.fresh_current_bundle_authority.v1"
)
SOURCE_AUTHORITY_STATUS = (
    "FRESH_CURRENT_SOURCE_BUNDLE_INDEPENDENTLY_VERIFIED"
)
BOUND_SOURCE_SCHEMA = (
    "gtos.replay_acceleration.bound_fresh_current_bundle_authority.v1"
)
PREPARED_PACK_SCHEMA = "gtos.replay_acceleration.prepared_day_pack.v1"
ARM_ORDER = ("S0R0", "S1R0", "S0R1", "S1R1")
RUNNER_OPTIONS = {
    "profile": "repaired_package_conversion_v3",
    "chunk_size": 1,
    "max_candidates_per_symbol_window": 0,
    "smoke_subset": False,
    "skip_tick_source": False,
    "use_native_h1": False,
    "omit_candidate_ledger": True,
    "omit_candidate_index_ledger": True,
    "omit_packet_sidecar_ledger": True,
    "compact_missed_ledger": True,
    "compact_decision_ledger": True,
    "compact_scorecard_ledger": True,
    "compact_event_sink": True,
    "compact_event_max_shard_bytes": 128 * 1024 * 1024,
    "prepared_day_pack": True,
    "candidate_relational_union": True,
    "gc_between_chunks": True,
    "source_prewarm_workers": 4,
    "broker_adapter": "SimulatedBroker",
    "broker_live_authority": False,
    "broker_mutation_enabled": False,
    "real_order_transmission_possible": False,
}
PACK_MANIFEST_FIELDS = {
    "schema",
    "status",
    "format",
    "compression",
    "max_shard_bytes",
    "max_record_bytes",
    "target_raw_shard_bytes",
    "bindings",
    "window_inventory",
    "record_count",
    "ordered_record_root_sha256",
    "shards",
    "pack_root_sha256",
}
PACK_SHARD_FIELDS = {
    "path",
    "shard_index",
    "row_count",
    "first_record_ordinal",
    "last_record_ordinal",
    "raw_bytes",
    "compressed_bytes",
    "raw_sha256",
    "compressed_sha256",
}
JSONL_ROLES = (
    "source",
    "decision",
    "scorecard",
    "order",
    "trade",
    "oracle",
    "missed",
    "bucket",
    "comparison",
)
JSON_ROLES = ("partial_summary", "summary")
REQUIRED_ROLES = JSONL_ROLES + JSON_ROLES
ROLE_SUFFIXES = {
    "source": "_SOURCE_UNIVERSE_LEDGER.jsonl",
    "decision": "_DECISION_LEDGER.jsonl",
    "scorecard": "_SCORECARD_LEDGER.jsonl",
    "order": "_ORDER_LEDGER.jsonl",
    "trade": "_TRADE_LEDGER.jsonl",
    "oracle": "_ORDERED_PATH_ORACLE_LEDGER.jsonl",
    "missed": "_MISSED_OPPORTUNITY_LEDGER.jsonl",
    "bucket": "_BUCKET_LEDGER.jsonl",
    "comparison": "_COMPARISON_LEDGER.jsonl",
    "partial_summary": "_PARTIAL_SUMMARY.json",
    "summary": "_SUMMARY.json",
}
HASH_CHUNK_BYTES = 16 * 1024 * 1024


class ArmVerificationError(RuntimeError):
    """Raised when any independent arm binding fails."""


def _require(condition: bool, code: str) -> None:
    if not condition:
        raise ArmVerificationError(code)


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def _stable_sha256(value: Any) -> str:
    return hashlib.sha256(_canonical_bytes(value)).hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb", buffering=0) as handle:
        for chunk in iter(lambda: handle.read(HASH_CHUNK_BYTES), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _is_sha256(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "009abcdef" for character in value)
    )


def _load_json(path: Path, *, code: str) -> dict[str, Any]:
    target = Path(os.path.abspath(path))
    _require(target.is_file() and not target.is_symlink(), code)
    try:
        value = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ArmVerificationError(code) from exc
    _require(isinstance(value, dict), code)
    return value


def _verify_root(payload: Mapping[str, Any], field: str, *, code: str) -> str:
    expected = payload.get(field)
    actual = _stable_sha256(
        {key: value for key, value in payload.items() if key != field}
    )
    _require(_is_sha256(expected) and expected == actual, code)
    return str(expected)


def _verify_decision_self_hash(
    decision: Mapping[str, Any],
) -> str:
    binding = decision.get("self_hash")
    _require(
        isinstance(binding, Mapping)
        and binding.get("algorithm") == "sha256"
        and binding.get("canonicalization")
        == "utf8_json_sort_keys_compact_separators_ensure_ascii"
        and binding.get("excluded_path") == "self_hash.sha256",
        "decision_contract_self_hash_invalid",
    )
    expected = binding.get("sha256")
    projection = copy.deepcopy(dict(decision))
    projection["self_hash"].pop("sha256", None)
    actual = _stable_sha256(projection)
    _require(
        _is_sha256(expected) and expected == actual,
        "decision_contract_self_hash_invalid",
    )
    return str(expected)


def _verify_source_authority(
    binding: Mapping[str, Any],
) -> dict[str, Any]:
    required = {
        "path",
        "file_sha256",
        "authority_root_sha256",
        "bundle_root_sha256",
        "selection_root_sha256",
        "source_plan_digest_sha256",
        "binding_root_sha256",
    }
    projection = {key: binding.get(key) for key in required}
    _require(
        all(_is_sha256(projection[key]) for key in required - {"path"}),
        "source_authority_binding_invalid",
    )
    authority_path = Path(str(projection["path"]))
    authority = _load_json(
        authority_path,
        code="source_authority_invalid",
    )
    authority_root = _verify_root(
        authority,
        "authority_root_sha256",
        code="source_authority_root_invalid",
    )
    bundle = authority.get("bundle")
    selection = authority.get("selection")
    _require(
        authority.get("schema") == SOURCE_AUTHORITY_SCHEMA
        and authority.get("status") == SOURCE_AUTHORITY_STATUS
        and authority.get("source_only") is True
        and authority.get("policy_execution_entered") is False
        and authority.get("economic_values_exposed") is False
        and authority.get("broker_live_authority") is False
        and authority.get("broker_mutation_enabled") is False
        and authority.get("real_order_transmission_possible") is False
        and _file_sha256(authority_path) == projection["file_sha256"]
        and authority_root == projection["authority_root_sha256"]
        and authority.get("source_plan_digest_sha256")
        == projection["source_plan_digest_sha256"]
        and isinstance(bundle, Mapping)
        and bundle.get("bundle_root_sha256")
        == projection["bundle_root_sha256"]
        and isinstance(selection, Mapping)
        and selection.get("selection_root_sha256")
        == projection["selection_root_sha256"],
        "source_authority_contract_invalid",
    )
    bundle_path = Path(str(bundle.get("path") or ""))
    selection_path = Path(str(selection.get("path") or ""))
    bundle_payload = _load_json(bundle_path, code="source_bundle_invalid")
    selection_payload = _load_json(
        selection_path,
        code="source_selection_invalid",
    )
    _require(
        bundle_path.parent == Path(str(bundle.get("directory") or ""))
        and _file_sha256(bundle_path) == bundle.get("file_sha256")
        and _verify_root(
            bundle_payload,
            "bundle_root_sha256",
            code="source_bundle_root_invalid",
        )
        == projection["bundle_root_sha256"]
        and _file_sha256(selection_path) == selection.get("file_sha256")
        and _verify_root(
            selection_payload,
            "selection_root_sha256",
            code="source_selection_root_invalid",
        )
        == projection["selection_root_sha256"],
        "source_authority_preimage_invalid",
    )
    binding_core = {
        "schema": BOUND_SOURCE_SCHEMA,
        "authority_path": str(authority_path.resolve()),
        "authority_file_sha256": projection["file_sha256"],
        "authority_root_sha256": projection["authority_root_sha256"],
        "authority": copy.deepcopy(authority),
        "verified_successor_bundle": {
            "path": str(bundle_path.resolve()),
            "file_sha256": bundle["file_sha256"],
            "bundle_root_sha256": projection["bundle_root_sha256"],
            "implementation_root_sha256": bundle[
                "accepted_cache_implementation_root"
            ],
        },
        "verified_successor_selection": {
            "path": str(selection_path.resolve()),
            "file_sha256": selection["file_sha256"],
            "selection_root_sha256": projection["selection_root_sha256"],
        },
        "source_plan_digest_sha256": projection[
            "source_plan_digest_sha256"
        ],
        "policy_execution_entered": False,
        "continuation_authorized": False,
        "broker_live_authority": False,
        "economic_values_exposed": False,
    }
    _require(
        _stable_sha256(binding_core) == projection["binding_root_sha256"],
        "source_authority_binding_root_invalid",
    )
    return projection


def _verify_prepared_pack_tree(
    *,
    authority: Mapping[str, Any],
) -> str:
    root = Path(str(authority.get("prepared_day_pack_root") or ""))
    declared_roots = authority.get("prepared_day_pack_roots")
    manifests = authority.get("manifest_bindings")
    builds = authority.get("prepared_day_packs")
    source_binding = authority.get("prepared_pack_source_identity_binding")
    _require(
        root.is_dir()
        and not root.is_symlink()
        and isinstance(declared_roots, Mapping)
        and bool(declared_roots)
        and isinstance(manifests, list)
        and isinstance(builds, list)
        and len(manifests) == len(builds) == len(declared_roots)
        and isinstance(source_binding, Mapping),
        "prepared_pack_inventory_invalid",
    )
    manifest_by_scope = {
        f"{row.get('split')}:{(row.get('days') or [''])[0]}:"
        f"{(row.get('days') or [''])[-1]}": row
        for row in manifests
        if isinstance(row, Mapping)
    }
    build_by_scope = {
        f"{row.get('split')}:{(row.get('days') or [''])[0]}:"
        f"{(row.get('days') or [''])[-1]}": row
        for row in builds
        if isinstance(row, Mapping)
    }
    _require(
        set(manifest_by_scope)
        == set(build_by_scope)
        == set(declared_roots),
        "prepared_pack_scope_inventory_invalid",
    )
    scope_identities: list[dict[str, Any]] = []
    actual_scopes: set[str] = set()
    root_entries = sorted(root.iterdir(), key=lambda path: path.name)
    _require(bool(root_entries), "prepared_pack_root_tree_invalid")
    for split_path in root_entries:
        _require(
            split_path.is_dir()
            and not split_path.is_symlink(),
            "prepared_pack_root_tree_invalid",
        )
        scope_paths = sorted(split_path.iterdir(), key=lambda path: path.name)
        _require(bool(scope_paths), "prepared_pack_root_tree_invalid")
        for scope_path in scope_paths:
            _require(
                scope_path.is_dir()
                and not scope_path.is_symlink(),
                "prepared_pack_root_tree_invalid",
            )
            entries = {path.name: path for path in scope_path.iterdir()}
            _require(
                set(entries)
                == {"PREPARED_DAY_PACK_MANIFEST.json", "SEALED", "shards"}
                and all(not path.is_symlink() for path in entries.values())
                and entries["PREPARED_DAY_PACK_MANIFEST.json"].is_file()
                and entries["SEALED"].is_file()
                and entries["shards"].is_dir(),
                "prepared_pack_root_tree_invalid",
            )
            manifest_path = entries["PREPARED_DAY_PACK_MANIFEST.json"]
            manifest = _load_json(
                manifest_path,
                code="prepared_pack_manifest_invalid",
            )
            bindings = manifest.get("bindings")
            days = (
                list(bindings.get("days") or ())
                if isinstance(bindings, Mapping)
                else []
            )
            scope = (
                f"{split_path.name}:{days[0]}:{days[-1]}"
                if days
                else ""
            )
            pack_root = _verify_root(
                manifest,
                "pack_root_sha256",
                code="prepared_pack_manifest_root_invalid",
            )
            _require(
                set(manifest) == PACK_MANIFEST_FIELDS
                and manifest.get("schema") == PREPARED_PACK_SCHEMA
                and manifest.get("status") == "SEALED"
                and manifest.get("format") == "ordered_canonical_jsonl_shards"
                and manifest.get("compression") == "zstd_level_1"
                and days
                and scope_path.name == f"{days[0]}_{days[-1]}"
                and declared_roots.get(scope) == pack_root
                and entries["SEALED"].read_text(encoding="ascii")
                == f"{pack_root}\n",
                "prepared_pack_manifest_contract_invalid",
            )
            manifest_binding = manifest_by_scope[scope]
            build = build_by_scope[scope]
            _require(
                Path(str(manifest_binding.get("path") or "")).resolve()
                == manifest_path.resolve()
                and manifest_binding.get("bytes") == manifest_path.stat().st_size
                and manifest_binding.get("file_sha256")
                == _file_sha256(manifest_path)
                and manifest_binding.get("pack_root_sha256") == pack_root
                and manifest_binding.get("source_identity_root_sha256")
                == bindings.get("source_identity_root_sha256")
                and manifest_binding.get(
                    "factor_neutral_config_root_sha256"
                )
                == bindings.get("factor_neutral_config_root_sha256")
                and build.get("pack_root_sha256") == pack_root
                and build.get("all_persisted_bytes_authenticated") is True
                and build.get("factor_reads_detected") is False,
                "prepared_pack_authority_scope_binding_invalid",
            )
            shards = manifest.get("shards")
            inventory = manifest.get("window_inventory")
            _require(
                isinstance(shards, list)
                and bool(shards)
                and isinstance(inventory, list)
                and len(inventory) == manifest.get("record_count"),
                "prepared_pack_manifest_inventory_invalid",
            )
            shard_entries = {
                path.name: path
                for path in entries["shards"].iterdir()
            }
            expected_names = {
                f"shard-{index:05d}.jsonl.zst"
                for index in range(len(shards))
            }
            _require(
                set(shard_entries) == expected_names
                and all(
                    path.is_file() and not path.is_symlink()
                    for path in shard_entries.values()
                ),
                "prepared_pack_shard_tree_invalid",
            )
            record_hashes: list[str] = []
            next_record = 0
            compressed_total = 0
            raw_total = 0
            for index, shard in enumerate(shards):
                name = f"shard-{index:05d}.jsonl.zst"
                path = shard_entries[name]
                compressed = path.read_bytes()
                _require(
                    isinstance(shard, Mapping)
                    and set(shard) == PACK_SHARD_FIELDS
                    and shard.get("path") == f"shards/{name}"
                    and shard.get("shard_index") == index
                    and shard.get("first_record_ordinal") == next_record
                    and len(compressed) == shard.get("compressed_bytes")
                    and hashlib.sha256(compressed).hexdigest()
                    == shard.get("compressed_sha256"),
                    "prepared_pack_compressed_identity_invalid",
                )
                try:
                    decompressor = zstd.ZstdDecompressor()
                    raw = decompressor.decompress(
                        compressed,
                        max_length=int(shard["raw_bytes"]) + 1,
                    )
                except (EOFError, zstd.ZstdError, ValueError) as exc:
                    raise ArmVerificationError(
                        "prepared_pack_raw_stream_invalid"
                    ) from exc
                lines = raw.splitlines(keepends=True)
                _require(
                    len(raw) == shard.get("raw_bytes")
                    and decompressor.eof
                    and not decompressor.unused_data
                    and hashlib.sha256(raw).hexdigest()
                    == shard.get("raw_sha256")
                    and len(lines) == shard.get("row_count")
                    and all(line.endswith(b"\n") for line in lines)
                    and shard.get("last_record_ordinal")
                    == next_record + len(lines) - 1,
                    "prepared_pack_raw_identity_invalid",
                )
                for line in lines:
                    record_hashes.append(
                        hashlib.sha256(line[:-1]).hexdigest()
                    )
                next_record += len(lines)
                compressed_total += len(compressed)
                raw_total += len(raw)
            inventory_hashes = [
                row.get("record_sha256")
                for row in inventory
                if isinstance(row, Mapping)
            ]
            _require(
                record_hashes == inventory_hashes
                and _stable_sha256(record_hashes)
                == manifest.get("ordered_record_root_sha256")
                and next_record == manifest.get("record_count")
                and build.get("record_count") == next_record
                and build.get("shard_count") == len(shards)
                and build.get("compressed_bytes") == compressed_total
                and build.get("raw_bytes") == raw_total,
                "prepared_pack_record_identity_invalid",
            )
            actual_scopes.add(scope)
            scope_identities.append(
                {
                    "scope": scope,
                    "pack_root_sha256": pack_root,
                    "manifest_file_sha256": _file_sha256(manifest_path),
                    "stored_shard_identity_root_sha256": _stable_sha256(
                        [
                            {
                                "path": shard["path"],
                                "compressed_bytes": shard[
                                    "compressed_bytes"
                                ],
                                "compressed_sha256": shard[
                                    "compressed_sha256"
                                ],
                                "raw_bytes": shard["raw_bytes"],
                                "raw_sha256": shard["raw_sha256"],
                            }
                            for shard in shards
                        ]
                    ),
                }
            )
    roots_by_scope = source_binding.get("roots_by_scope")
    _require(
        actual_scopes == set(declared_roots)
        and isinstance(roots_by_scope, Mapping)
        and set(roots_by_scope) == actual_scopes
        and roots_by_scope
        == {
            scope: manifest_by_scope[scope][
                "source_identity_root_sha256"
            ]
            for scope in sorted(actual_scopes)
        }
        and source_binding.get("scope_count") == len(actual_scopes)
        and source_binding.get("all_scope_roots_explicitly_bound") is True
        and source_binding.get("binding_root_sha256")
        == _stable_sha256(dict(sorted(roots_by_scope.items()))),
        "prepared_pack_source_identity_binding_invalid",
    )
    return _stable_sha256(scope_identities)


def _verify_pack_authority(
    *,
    receipt_binding: Mapping[str, Any],
    seal_binding: Mapping[str, Any],
    decision_path: Path,
    decision_root: str,
    execution_source_binding: Mapping[str, Any],
    window_binding: Mapping[str, Any],
) -> dict[str, Any]:
    receipt_required = {
        "path",
        "file_sha256",
        "authority_root_sha256",
        "prepared_day_pack_root",
        "prepared_day_pack_roots",
    }
    seal_required = {
        "authority_path",
        "authority_file_sha256",
        "authority_root_sha256",
        "prepared_day_pack_root",
        "prepared_day_pack_roots",
        "source_authority_binding",
    }
    _require(
        set(receipt_binding) == receipt_required
        and set(seal_binding) >= seal_required
        and receipt_binding["path"] == seal_binding["authority_path"]
        and receipt_binding["file_sha256"]
        == seal_binding["authority_file_sha256"]
        and receipt_binding["authority_root_sha256"]
        == seal_binding["authority_root_sha256"]
        and receipt_binding["prepared_day_pack_root"]
        == seal_binding["prepared_day_pack_root"]
        and receipt_binding["prepared_day_pack_roots"]
        == seal_binding["prepared_day_pack_roots"],
        "prepared_pack_receipt_seal_binding_mismatch",
    )
    authority_path = Path(str(receipt_binding["path"]))
    authority = _load_json(
        authority_path,
        code="prepared_pack_authority_invalid",
    )
    authority_root = _verify_root(
        authority,
        "authority_root_sha256",
        code="prepared_pack_authority_root_invalid",
    )
    decision_binding = authority.get("decision_contract_binding")
    authority_source = authority.get("source_authority_binding")
    source_equivalence = authority.get(
        "source_selection_semantic_equivalence"
    )
    pack_transport = authority.get(
        "predecessor_pack_build_transport_reconciliation"
    )
    _require(
        _file_sha256(authority_path)
        == receipt_binding["file_sha256"]
        == seal_binding["authority_file_sha256"]
        and authority_root
        == receipt_binding["authority_root_sha256"]
        == seal_binding["authority_root_sha256"]
        and authority.get("prepared_day_pack_root")
        == receipt_binding["prepared_day_pack_root"]
        and authority.get("prepared_day_pack_roots")
        == receipt_binding["prepared_day_pack_roots"]
        and authority.get("schema") == PACK_AUTHORITY_SCHEMA
        and authority.get("status") == PACK_AUTHORITY_STATUS
        and authority.get("valid") is True
        and authority.get("window_binding") == window_binding
        and authority.get("all_persisted_pack_bytes_authenticated") is True
        and authority.get("factor_reads_forbidden_and_audited") is True
        and authority.get("factorial_values_present_in_preparation_config")
        is False
        and authority.get("policy_execution_entered") is False
        and authority.get("broker_live_authority") is False
        and authority.get("broker_mutation_enabled") is False
        and authority.get("real_order_transmission_possible") is False
        and authority.get("economic_values_exposed") is False
        and isinstance(decision_binding, Mapping)
        and decision_binding.get("file_sha256") == _file_sha256(decision_path)
        and decision_binding.get("self_hash_sha256") == decision_root
        and isinstance(authority_source, Mapping)
        and dict(authority_source) == dict(execution_source_binding)
        and seal_binding.get("source_authority_binding")
        == dict(execution_source_binding)
        and isinstance(source_equivalence, Mapping)
        and source_equivalence.get("status") == "EXACT_RETAINED_FIELDS_EQUAL"
        and source_equivalence.get("meaningful_source_difference_count") == 0
        and source_equivalence.get("unknown_difference_count") == 0
        and isinstance(pack_transport, Mapping)
        and pack_transport.get("status")
        in {
            "PACK_BUILD_TRANSPORT_DIRECTLY_SEALED",
            "LEGACY_PACK_BUILD_TRANSPORT_EXACTLY_RECONCILED",
        }
        and pack_transport.get("meaningful_difference_count") == 0
        and pack_transport.get("unknown_difference_count") == 0
        and pack_transport.get("original_seal_relabelled") is False,
        "prepared_pack_authority_binding_invalid",
    )
    pack_byte_identity_root = _verify_prepared_pack_tree(authority=authority)
    return {
        "authority_file_sha256": receipt_binding["file_sha256"],
        "authority_root_sha256": authority_root,
        "prepared_day_pack_roots_sha256": _stable_sha256(
            receipt_binding["prepared_day_pack_roots"]
        ),
        "prepared_pack_stored_byte_identity_root_sha256": (
            pack_byte_identity_root
        ),
        "all_declared_pack_bytes_independently_authenticated": True,
    }


def _verify_execution_contract(
    *,
    execution_path: Path,
    decision_path: Path,
    decision: Mapping[str, Any],
    decision_root: str,
) -> tuple[dict[str, Any], str, dict[str, Any]]:
    execution = _load_json(
        execution_path,
        code="execution_seal_invalid",
    )
    execution_root = _verify_root(
        execution,
        "execution_seal_root_sha256",
        code="execution_seal_root_invalid",
    )
    decision_binding = execution.get("decision_contract_binding")
    source_binding = execution.get("source_authority_binding")
    pack_binding = execution.get("prepared_day_pack_binding")
    arms = execution.get("arms")
    _require(
        execution.get("schema") == EXECUTION_SCHEMA
        and execution.get("status") == EXECUTION_STATUS
        and execution.get("valid") is True
        and execution.get("replay_free_builder") is True
        and execution.get("run_campaign_call_count") == 0
        and execution.get("outcome_ledger_read_count") == 0
        and execution.get("outcome_artifact_read_count") == 0
        and execution.get("march_outcome_read") is False
        and execution.get("runner_options") == RUNNER_OPTIONS
        and execution.get("all_four_arm_shared_digests_unique") is True
        and execution.get("broker_live_authority") is False
        and execution.get("broker_mutation_enabled") is False
        and execution.get("real_order_transmission_possible") is False
        and execution.get("economic_values_exposed") is False
        and isinstance(decision_binding, Mapping)
        and decision_binding.get("file_sha256") == _file_sha256(decision_path)
        and decision_binding.get("self_hash_sha256") == decision_root
        and decision_binding.get("schema") == decision.get("schema")
        and decision_binding.get("status") == decision.get("status")
        and isinstance(source_binding, Mapping)
        and source_binding.get("fresh_current_bundle") is True
        and source_binding.get("policy_execution_entered") is False
        and isinstance(pack_binding, Mapping)
        and pack_binding.get("required") is True
        and pack_binding.get("arm_neutral") is True
        and pack_binding.get("factor_reads_forbidden") is True
        and pack_binding.get(
            "all_persisted_pack_bytes_authenticated_before_seal"
        )
        is True
        and isinstance(arms, Mapping)
        and set(arms) == set(ARM_ORDER),
        "execution_seal_contract_invalid",
    )
    arm_digests: set[str] = set()
    for arm_id in ARM_ORDER:
        arm = arms[arm_id]
        _require(
            isinstance(arm, Mapping)
            and set(arm)
            == {
                "arm_fingerprint_sha256",
                "factorial_binding_payload_sha256",
                "shared_execution_contract_digest_sha256",
                "code_authority_root_sha256",
                "exact_profile_config_root_sha256",
            }
            and all(_is_sha256(value) for value in arm.values()),
            "execution_seal_arm_inventory_invalid",
        )
        arm_digests.add(arm["shared_execution_contract_digest_sha256"])
    _require(
        len(arm_digests) == len(ARM_ORDER),
        "execution_seal_arm_digest_collision",
    )
    source_projection = {
        key: source_binding.get(key)
        for key in {
            "path",
            "file_sha256",
            "authority_root_sha256",
            "bundle_root_sha256",
            "selection_root_sha256",
            "source_plan_digest_sha256",
            "binding_root_sha256",
        }
    }
    _verify_source_authority(source_projection)
    return execution, execution_root, source_projection


def _verify_artifacts(
    *,
    namespace: Path,
    output_prefix: str,
    inventory: Mapping[str, Any],
) -> tuple[str, str]:
    artifacts = inventory.get("artifacts")
    _require(
        isinstance(artifacts, Mapping)
        and set(artifacts) == set(REQUIRED_ROLES)
        and inventory.get("artifact_count") == len(REQUIRED_ROLES),
        "artifact_inventory_roles_invalid",
    )
    inventory_root = _verify_root(
        inventory,
        "inventory_root_sha256",
        code="artifact_inventory_root_invalid",
    )
    resolver = RawOrColdResolver()
    verified: dict[str, Any] = {}
    expected_entries = {"B7_5_POST_ACCELERATION_ARM_RECEIPT.json"}

    for role in REQUIRED_ROLES:
        row = artifacts[role]
        _require(isinstance(row, Mapping), f"artifact_inventory_row_invalid:{role}")
        expected_name = f"{output_prefix}{ROLE_SUFFIXES[role]}"
        _require(
            row.get("path") == expected_name
            and Path(expected_name).name == expected_name,
            f"artifact_path_invalid:{role}",
        )
        logical_path = namespace / expected_name
        expected_entries.add(expected_name)
        if role in JSONL_ROLES:
            try:
                metadata = resolver.logical_metadata(
                    logical_path,
                    verify_full=True,
                    parse_json=False,
                )
            except ColdEvidenceError as exc:
                raise ArmVerificationError(
                    f"artifact_verification_failed:{role}:{exc}"
                ) from exc
            if metadata["storage_mode"] == "cold_zstd_shards":
                expected_entries.remove(expected_name)
                expected_entries.add(f"{expected_name}.cold")
            expected_identity = (
                row.get("bytes"),
                row.get("sha256"),
                row.get("rows"),
            )
            actual_identity = (
                metadata.get("logical_bytes"),
                metadata.get("sha256"),
                metadata.get("physical_line_count"),
            )
            _require(
                expected_identity == actual_identity
                and metadata.get("json_object_row_count") == row.get("rows")
                and metadata.get("blank_line_count") == 0
                and (
                    row.get("bytes") == 0
                    or metadata.get("ends_with_lf") is True
                ),
                f"artifact_logical_identity_mismatch:{role}",
            )
            verified[role] = {
                "logical_path": expected_name,
                "storage_mode": metadata["storage_mode"],
                "bytes": metadata["logical_bytes"],
                "sha256": metadata["sha256"],
                "rows": metadata["physical_line_count"],
            }
            continue

        _require(
            logical_path.is_file()
            and not logical_path.is_symlink()
            and not logical_path.with_name(logical_path.name + ".cold").exists(),
            f"artifact_file_invalid:{role}",
        )
        actual_bytes = logical_path.stat().st_size
        actual_sha256 = _file_sha256(logical_path)
        _require(
            row.get("bytes") == actual_bytes
            and row.get("sha256") == actual_sha256,
            f"artifact_logical_identity_mismatch:{role}",
        )
        verified[role] = {
            "logical_path": expected_name,
            "storage_mode": "raw",
            "bytes": actual_bytes,
            "sha256": actual_sha256,
        }

    actual_entries = {path.name for path in namespace.iterdir()}
    _require(
        actual_entries == expected_entries,
        "arm_namespace_artifact_set_invalid",
    )
    logical_identities = {
        role: {
            key: value
            for key, value in row.items()
            if key != "storage_mode"
        }
        for role, row in verified.items()
    }
    return _stable_sha256(logical_identities), inventory_root


def _verify_divergence_matrix_input(
    *, matrix_path: Path, receipt: Mapping[str, Any]
) -> dict[str, Any]:
    """Bind this arm's divergence matrix, or refuse the arm.

    `CLAUDE.md` H7: replay does not measure the live system, and replay R must not be
    transferred to a production claim without the matrix.  Making that a *required*
    input is the whole point — an artifact merely produced beside a receipt gets
    ignored, so acceptance fails closed without one.

    The matrix lives outside the arm namespace deliberately.  `build_arm_artifact_
    inventory` (`b7_5_post_acceleration_runner.py:366-369`) asserts the namespace
    contains exactly the eleven expected artifact roles, so a twelfth file there would
    fail the arm with `post_acceleration_output_artifact_set_invalid`.
    """

    path = Path(os.path.abspath(matrix_path))
    matrix = _load_json(path, code="divergence_matrix_invalid")
    _require(
        matrix.get("schema") == DIVERGENCE_MATRIX_SCHEMA,
        "divergence_matrix_schema_invalid",
    )
    try:
        verify_divergence_matrix(matrix, arm_receipt=receipt)
    except DivergenceMatrixError as exc:
        raise ArmVerificationError(str(exc)) from None
    return {
        "path": str(path),
        "file_sha256": _file_sha256(path),
        "matrix_root_sha256": matrix["matrix_root_sha256"],
        "transfer_verdict": matrix["transfer_verdict"],
        "row_count": matrix["counts"]["rows"],
        "unknown_direction_count": matrix["counts"]["unknown_direction"],
        "unquantified_count": matrix["counts"]["unquantified"],
        "blocks_transfer_count": matrix["counts"]["blocks_transfer"],
        "declared_row_count": matrix["counts"]["declared"],
    }


def verify_arm(
    *,
    arm_receipt_path: Path,
    decision_contract_path: Path,
    execution_seal_path: Path,
    divergence_matrix_path: Path,
) -> dict[str, Any]:
    """Return an outcome-blind exact logical-byte verification receipt."""

    receipt_path = Path(os.path.abspath(arm_receipt_path))
    receipt = _load_json(receipt_path, code="arm_receipt_invalid")
    receipt_root = _verify_root(
        receipt,
        "receipt_root_sha256",
        code="arm_receipt_root_invalid",
    )
    _require(
        receipt.get("schema") == RECEIPT_SCHEMA
        and receipt.get("status") == RECEIPT_STATUS
        and receipt.get("broker_live_authority") is False
        and receipt.get("broker_mutation_enabled") is False
        and receipt.get("real_order_transmission_possible") is False
        and receipt.get("economic_values_exposed") is False,
        "arm_receipt_contract_invalid",
    )
    namespace = Path(str(receipt.get("namespace") or ""))
    _require(
        namespace.is_dir()
        and not namespace.is_symlink()
        and receipt_path.parent == namespace
        and receipt_path.name == "B7_5_POST_ACCELERATION_ARM_RECEIPT.json",
        "arm_receipt_namespace_invalid",
    )

    decision_path = Path(os.path.abspath(decision_contract_path))
    decision = _load_json(decision_path, code="decision_contract_invalid")
    decision_root = _verify_decision_self_hash(decision)
    authority_boundary = decision.get("authority_boundary")
    _require(
        decision.get("schema") == DECISION_SCHEMA
        and decision.get("status") == DECISION_STATUS
        and isinstance(authority_boundary, Mapping)
        and authority_boundary.get("decision_contract_only") is True
        and authority_boundary.get("replay_launched") is False
        and authority_boundary.get("outcomes_evaluated") is False
        and authority_boundary.get("broker_live_final_authority") is False
        and authority_boundary.get("broker_mutation_enabled") is False
        and authority_boundary.get("real_order_transmission_possible") is False
        and receipt.get("decision_contract_self_hash_sha256") == decision_root,
        "arm_receipt_decision_contract_mismatch",
    )

    execution_path = Path(os.path.abspath(execution_seal_path))
    execution, execution_root, execution_source = (
        _verify_execution_contract(
            execution_path=execution_path,
            decision_path=decision_path,
            decision=decision,
            decision_root=decision_root,
        )
    )
    arm_id = receipt.get("arm_id")
    arm = (execution.get("arms") or {}).get(arm_id)
    _require(
        isinstance(arm_id, str)
        and isinstance(arm, Mapping)
        and receipt.get("execution_seal_root_sha256") == execution_root
        and receipt.get("arm_fingerprint_sha256")
        == arm.get("arm_fingerprint_sha256")
        and receipt.get("shared_execution_contract_digest_sha256")
        == arm.get("shared_execution_contract_digest_sha256")
        and receipt.get("window") == execution.get("window_binding")
        and receipt.get("source_authority_binding_root_sha256")
        == execution_source["binding_root_sha256"],
        "arm_receipt_execution_seal_mismatch",
    )
    receipt_pack = receipt.get("prepared_pack_authority")
    seal_pack = execution.get("prepared_day_pack_binding")
    _require(
        isinstance(receipt_pack, Mapping) and isinstance(seal_pack, Mapping),
        "prepared_pack_binding_missing",
    )
    verified_pack = _verify_pack_authority(
        receipt_binding=receipt_pack,
        seal_binding=seal_pack,
        decision_path=decision_path,
        decision_root=decision_root,
        execution_source_binding=execution_source,
        window_binding=execution["window_binding"],
    )

    inventory = receipt.get("artifact_inventory")
    _require(isinstance(inventory, Mapping), "artifact_inventory_invalid")
    output_prefix = receipt.get("output_prefix")
    _require(
        isinstance(output_prefix, str)
        and output_prefix
        and Path(output_prefix).name == output_prefix,
        "arm_output_prefix_invalid",
    )
    artifact_identity_root, inventory_root = _verify_artifacts(
        namespace=namespace,
        output_prefix=output_prefix,
        inventory=inventory,
    )
    divergence_matrix = _verify_divergence_matrix_input(
        matrix_path=divergence_matrix_path,
        receipt=receipt,
    )
    core = {
        "schema": SCHEMA,
        "status": PASS_STATUS,
        "arm_id": arm_id,
        "window": receipt["window"],
        "arm_receipt": {
            "path": str(receipt_path),
            "file_sha256": _file_sha256(receipt_path),
            "receipt_root_sha256": receipt_root,
        },
        "decision_contract": {
            "path": str(decision_path),
            "file_sha256": _file_sha256(decision_path),
            "self_hash_sha256": decision_root,
        },
        "execution_seal": {
            "path": str(execution_path),
            "file_sha256": _file_sha256(execution_path),
            "execution_seal_root_sha256": execution_root,
        },
        "prepared_pack_authority": verified_pack,
        "divergence_matrix": divergence_matrix,
        "artifact_inventory_root_sha256": inventory_root,
        "verified_artifact_identity_root_sha256": artifact_identity_root,
        "artifact_count": len(REQUIRED_ROLES),
        "outcome_bearing_counts_emitted": False,
        "all_logical_bytes_verified": True,
        "all_hashes_and_row_counts_match_producer_receipt": True,
        "economic_json_objects_decoded": 0,
        "economic_values_decoded_or_emitted": False,
        "broker_live_authority": False,
        "broker_mutation_enabled": False,
        "real_order_transmission_possible": False,
    }
    return {**core, "verification_root_sha256": _stable_sha256(core)}


def _write_json_atomic(path: Path, value: Mapping[str, Any]) -> None:
    target = Path(os.path.abspath(path))
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        with temporary.open("w", encoding="utf-8") as handle:
            json.dump(value, handle, indent=2, sort_keys=True, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, target)
    finally:
        if temporary.exists():
            temporary.unlink()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arm-receipt", type=Path, required=True)
    parser.add_argument("--decision-contract", type=Path, required=True)
    parser.add_argument("--execution-seal", type=Path, required=True)
    parser.add_argument(
        "--divergence-matrix",
        type=Path,
        required=True,
        help=(
            "arm-bound divergence matrix from src/research_infra/divergence_matrix.py. "
            "Required: an arm is not accepted without a statement of how the replay "
            "path differs from the live one (CLAUDE.md H7)."
        ),
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    return parser


def main() -> int:
    args = _parser().parse_args()
    result = verify_arm(
        arm_receipt_path=args.arm_receipt,
        decision_contract_path=args.decision_contract,
        execution_seal_path=args.execution_seal,
        divergence_matrix_path=args.divergence_matrix,
    )
    output = Path(os.path.abspath(args.output))
    if args.check:
        observed = _load_json(output, code="verification_receipt_missing_or_invalid")
        _require(
            observed == result,
            "verification_receipt_recomputation_mismatch",
        )
    else:
        _require(
            not os.path.lexists(output),
            "verification_output_must_be_new",
        )
        _write_json_atomic(output, result)
    print(
        json.dumps(
            {
                "status": result["status"],
                "arm_id": result["arm_id"],
                "artifact_count": result["artifact_count"],
                "transfer_verdict": result["divergence_matrix"]["transfer_verdict"],
                "verification_root_sha256": result[
                    "verification_root_sha256"
                ],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
