#!/usr/bin/env python3
"""Generate `phase11/EXIT_CONTRACT_ACTIVATION_DOSSIER.md` from AS_EXIT_CONTRACT_ACTIVATION_V1.json.

Every figure is read out of the artifact. Nothing is transcribed; if an input moves this generator
dies rather than printing a stale number.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[5]
AUDIT = REPO / "docs/audits/fable5-vision-audit-20260725"
SRC = AUDIT / "phase11/receipts/AS_EXIT_CONTRACT_ACTIVATION_V1.json"
OUT = AUDIT / "phase11/EXIT_CONTRACT_ACTIVATION_DOSSIER.md"

D = json.loads(SRC.read_text())
NO = D["noop"]
BL = D["blast"]
MB = D["membership"]
TK = D["token"]
RG = D["regate"]
SZ = D["sizing"]
A = RG["arms"]

BTC = "mx_btcusd_d1_donchian_20_breakout"
XVOL = "sub_xvol_pullback"

L: list[str] = []
w = L.append


def arm(v, pop, band, fam="V5_48"):
    return A[f"{v}|{pop}|{band}|{fam}"]


w("# The exit-contract activation dossier — `mx_btcusd @ target_5R` and `sub_xvol_pullback @ target_4R`")
w("")
w("**Session AS, blocks B1520–B1539.** Generated by")
w("`phase11/receipts/as_activation_dossier.py` from")
w("`phase11/receipts/AS_EXIT_CONTRACT_ACTIVATION_V1.json`; every figure is read out of that")
w("artifact and none is transcribed.")
w("")
w("These are the next two live changes and **they are CONTRACT changes, not tag changes.** The")
w("five-sleeve expansion moved a string in a launch command and no config byte; these move Python")
w("that decides where a broker take-profit is placed. This page arms nothing. It says exactly what")
w("each change is, what it costs, what it cannot break, and — for one of the two — that it is not")
w("ready to be proposed.")
w("")
w("---")
w("")

# =====================================================================================
w("## 0. The finding that governs both changes")
w("")
w("**Editing `final_target_r` in `SLEEVE_EXIT_PROFILES` is a NO-OP for the entire `mx_*` cohort,**")
w("and an activation package that did only that would arm `mx_btcusd` on the 2R contract its own")
w("evidence REJECTS at every band — while **the spec, the diff and the commit message all said")
w("5R**.")
w("")
w("> **Corrected after an adversarial pass.** A first cut of this page said *\"every log would say")
w("> 5R\"*, and that is false and matters: the runtime logs read the **resolved** value, so they")
w("> would correctly say 2.0. The deception is in the *source*, not in the telemetry — which is")
w("> better news for anyone watching a live book and worse news for anyone reviewing a diff.")
w("")
w(f"The mechanism: {NO['mechanism']}.")
w("")
w("Proved behaviourally by driving the real `build_book_trade_params` under three profile states:")
w("")
w("| profile state | resolved `final_target_r` | broker TP on a 100,000 entry with a 1,000 stop |")
w("|---|---:|---:|")
for label, key in (("as committed (`final_target_r=2.0`, `final_from_intent=True`)", "committed"),
                   ("**the naive edit**: `final_target_r=5.0`", "naive_edit_final_target_r_5"),
                   ("`final_target_r=5.0` **and** `final_from_intent` removed",
                    "correct_edit_drop_final_from_intent"),
                   ("generator route: `market_expansion_d1.TARGET_R = 5.0`",
                    "generator_edit_TARGET_R_5")):
    r = NO["mx_btcusd"][key]
    w(f"| {label} | {r['final_target_r']} | {r['take_profit_1']:,.0f} |")
w("")
w(f"`sub_xvol_pullback` is not exposed to this: its profile carries no `final_from_intent`, so the")
w(f"same edit resolves as written — 3.0 → "
  f"{NO['sub_xvol_pullback']['edit_final_target_r_4']['final_target_r']}.")
w("")
w(f"> {NO['consequence']}")
w("")
w("(The artifact's `consequence` field carries the same first-cut phrasing about logs; the")
w("correction above governs.)")
w("")

# =====================================================================================
w("## 1. `mx_btcusd @ target_5R` — the exact spec diff")
w("")
w("**Two routes reach the 5R contract, and they are not equivalent.**")
w("")
w("### Route A — the profile route (RECOMMENDED)")
w("")
w("```python")
w("# src/components/ultimate_book/execution_packets.py")
w("# after the MARKET_EXPANSION_TARGET2_SLEEVES block that sets the cohort default:")
w("SLEEVE_EXIT_PROFILES[\"mx_btcusd_d1_donchian_20_breakout\"] = dict(")
w("    policy=\"time_stop\",")
w("    final_target_r=5.0,          # the admission's own cell")
w("    #  NO `final_from_intent` — with it the generator's 2R wins and this line is dead")
w("    time_stop_bars=time_stop_m15(RESEARCH_HORIZON_NATIVE_BARS, \"D1\"),   # 7680, unchanged")
w(")")
w("```")
w("")
bl_a = BL["mx_btcusd_profile_route"]
w(f"**Blast radius, measured** by resolving all {bl_a['n_sleeves_in_registry']} registered sleeves'")
w(f"exit fields before and after, through **both** production resolvers: "
  f"**{bl_a['n_moved']} sleeve moves**, it is the one named, and")
w(f"**{len(bl_a['armed_sleeves_moved'])} armed sleeves move.** Change class")
w(f"`{bl_a['change_class']}`.")
w("")
w("> **There are TWO resolvers and only one honours `final_from_intent`.** "
  "`build_book_trade_params` (`:249-256`) does; `native_policy_instrumentation` (`:152-181`, the")
w("> adopt-missing-record rehydration path) reads `final_target_r` at `:165-166` **unguarded**. So")
w("> under the *naive* edit the two DISAGREE — 2R at the broker, 5R in the rehydration payload,")
w("> which `book_owner.py:2724` persists. That divergence used to be inert because the hydrator")
w("> raised `KeyError('trigger_r')` before reaching the broker; **this session fixed that (B1535),")
w("> so it is now reachable.** Route A is the recommendation partly for this reason: dropping")
w("> `final_from_intent` is the only form of the change under which both resolvers carry the same")
w("> number. Pinned by three tests. A first cut of this dossier measured the blast radius through")
w("> one resolver only — an adversarial pass found it.")
w("")
w("### Route B — the generator route (NOT recommended)")
w("")
bl_b = BL["mx_btcusd_generator_route"]
w(f"Changing `market_expansion_d1.TARGET_R` from {NO['generator_TARGET_R']} to 5.0 also produces a")
w(f"5R contract — but `TARGET_R` is a **module constant shared by every `mx_*` generator**, so it")
w(f"moves **{bl_b['n_sleeves_that_would_move']} sleeves**, not one. It cannot be scoped to")
w("`mx_btcusd` without a further code change. Route A is one dict entry with a blast radius of one.")
w("")
w("### What does NOT change")
w("")
w("`time_stop_bars` stays at 7680 — AQ's repair, landed at B1404. **The admission is a property of")
w("both changes together**: at mid band, the time-stop repair alone gives p 0.0064 (REJECT), the 5R")
w("target alone under the old one-bar stop gives p 0.0564 (REJECT), and both together give")
w("p 0.0011 (ADMIT). Any package citing this cell must name the repair as well as the target.")
w("")

# =====================================================================================
w("## 2. `sub_xvol_pullback @ target_4R` — and why this one is NOT ready")
w("")
w("This is a change to an **ARMED** sleeve's live contract. Two things have to be said before the")
w("diff, and the second one is why the change is not proposed today.")
w("")
w("### 2a. The headline figure is widely misread, including in this session's own commission")
w("")
w(f"> {RG['the_number_that_is_widely_misread']}")
w("")
w("### 2b. AK measured this cell at a standard that does not govern the estate — so it was re-gated")
w("")
w("AK's frontier carries **no population key and no `spread_band` key**, which means ALL_ERAS at the")
w("flat 37-day snapshot, at the historical 69-look family. The estate's ratified standard is")
w("**RECORDED, banded, at `CANDIDATE_BOOK_V1`**. This session ran that.")
w("")
ctrl = RG["control"]
w("**Control first**: AK's published cell reproduces here to the digit at ALL_ERAS / flat —")
w(f"R/day {ctrl['ak_published']['pooled_oos_mean_r']:.10f}, p")
w(f"{ctrl['ak_published']['p_raw']:.10f}. `r_per_day_reproduces`")
w(f"**{ctrl['r_per_day_reproduces']}**, `p_reproduces` **{ctrl['p_reproduces']}**. So any difference")
w("below is the standard, not the instrument.")
w("")
w("| population | band | `as_walked` (= the live 3R contract) | `target_4R` | Δ | verdict | p_raw | q at family 48 |")
w("|---|---|---:|---:|---:|---|---:|---:|")
for pop in ("RECORDED", "ALL_ERAS"):
    for band in ("flat", "low", "mid", "high"):
        aw, t4 = arm("as_walked", pop, band), arm("target_4R", pop, band)
        star = " *(control)*" if band == "flat" else ""
        w(f"| {pop} | {band}{star} | {aw['pooled_oos_mean_r']:.4f} | "
          f"{t4['pooled_oos_mean_r']:.4f} | **{t4['pooled_oos_mean_r'] - aw['pooled_oos_mean_r']:+.4f}** | "
          f"{t4['verdict']} | {t4['p_raw']:.6f} | {t4['q_value']:.4f} |")
w("")
r_mid, a_mid = arm("target_4R", "RECORDED", "mid"), arm("as_walked", "RECORDED", "mid")
e_mid = arm("target_4R", "ALL_ERAS", "mid")
ea_mid = arm("as_walked", "ALL_ERAS", "mid")
w("**Three things that table says, in order of how much they matter:**")
w("")
w(f"1. **The change is worth MORE at the ratified rule, not less.** "
  f"{r_mid['pooled_oos_mean_r'] - a_mid['pooled_oos_mean_r']:+.4f} R/day on RECORDED against "
  f"{e_mid['pooled_oos_mean_r'] - ea_mid['pooled_oos_mean_r']:+.4f} on ALL_ERAS — "
  f"{(r_mid['pooled_oos_mean_r'] - a_mid['pooled_oos_mean_r']) / (e_mid['pooled_oos_mean_r'] - ea_mid['pooled_oos_mean_r']):.1f}×. "
  f"The delta is identical across all four bands, which is expected and is a check: the band charges "
  f"spread, both arms hold the same entries, so the spread term cancels in the difference.")
w("")
w(f"2. **`as_walked` and the sleeve's declared 3R target are the SAME arm to the digit** "
  f"({arm('target_3R_live', 'RECORDED', 'mid')['pooled_oos_mean_r']:.4f} R/day, p "
  f"{arm('target_3R_live', 'RECORDED', 'mid')['p_raw']:.6f}). That is a live-contract fidelity "
  f"confirmation worth having on an armed sleeve: the walk's baseline IS what the book runs.")
w("")
w(f"3. **It still REJECTS at every band.** {arm('target_4R','RECORDED','mid')['reasons'][0]} The raw "
  f"p is {r_mid['p_raw']:.6f} against a BH rank-1 bar of "
  f"{0.10/48:.6f} — **{r_mid['p_raw']/(0.10/48):.1f}× ABOVE it**, not a near miss.")
w("")
w("### 2c. The change also buys carry, and this sleeve's largest cost term is swap")
w("")
cc = RG["carry_consequence"]
w("| | `as_walked` | `target_4R` |")
w("|---|---:|---:|")
w(f"| mean swap nights | {cc['swap_nights_mean_as_walked']} | {cc['swap_nights_mean_target_4R']} |")
w(f"| median hold (h) | {cc['median_hold_hours_as_walked']} | {cc['median_hold_hours_target_4R']} |")
w(f"| swap share of cost | {cc['swap_share_of_cost_as_walked']:.3f} | "
  f"{cc['swap_share_of_cost_target_4R']:.3f} |")
w("")
w(f"{cc['note']}")
w("")
w("### 2d. The maxbars share, declared — on the POPULATION-FILTERED rows")
w("")
w("The wave-12 delta: an exit sweep that does not report its truncation share is quoting a")
w("frontier it has not priced. At the ratified rule (RECORDED):")
w("")
w("| cell | maxbars / n | share | share on the pre-population set |")
w("|---|---:|---:|---:|")
for v in ("as_walked", "target_4R"):
    a = arm(v, "RECORDED", "mid")
    w(f"| `{v}` | {a['n_maxbars']} / {a['n']} | {a['maxbars_share']:.4f} | "
      f"{a['maxbars_share_pre_population']:.4f} |")
w("")
w("> A first cut of this driver stamped the **pre-population** row set onto every arm, so each")
w("> RECORDED arm reported `n: 88` beside `n_trades: 85`. Caught by an adversarial pass; the")
w("> numbers above are the filtered ones and both are published so the difference is visible.")
w("")
w("**And the population attribution, stated because the +0.3435 rests on it.** `RECORDED` drops")
w("exactly **3 of the 88** trades, and here they are:")
w("")
w("| symbol | entry | `r_gross` | exit |")
w("|---|---|---:|---|")
w("| `US500.cash` | 2021-07-08 | +3.0000 | target |")
w("| `JP225.cash` | 2023-03-10 | −1.0000 | stop |")
w("| `XAUEUR` | 2023-03-21 | +3.0000 | target |")
w("")
w("Two of the three are **+3R target hits under the native contract** — precisely the trades whose")
w("behaviour a 4R target changes. So the amplification of the delta from +0.1301 to +0.3435 rests")
w("on three excluded trades out of 88, and this session did **not** run the per-trade attribution.")
w("The three are named so that anyone can. On a REJECT that changes nothing; on an admission it")
w("would have to be run first.")
w("")
w("### 2e. The diff, for when it is ready")
w("")
w("```python")
w("# src/components/ultimate_book/execution_packets.py:84")
w("-\"sub_xvol_pullback\": dict(policy=\"time_stop\", final_target_r=3.0,  time_stop_bars=1280),")
w("+\"sub_xvol_pullback\": dict(policy=\"time_stop\", final_target_r=4.0,  time_stop_bars=1280),")
w("```")
w("")
bl_x = BL["sub_xvol_target_4R"]
w(f"**Blast radius, measured: {bl_x['n_moved']} sleeve moves and it is the one named.** But")
w(f"`armed_sleeves_moved` is `{bl_x['armed_sleeves_moved']}` and the change class is")
w(f"**`{bl_x['change_class']}`** — that is not a defect, it is the entire reason this needs an owner")
w("decision rather than a merge.")
w("")
w("> **RECOMMENDATION: do not propose this change yet.** It is a REJECT at the ratified rule at")
w("> every band, 3.8× outside the rank-1 bar, on an armed sleeve, and it increases carry on the")
w("> sleeve whose cost is 54–65 % swap. The +0.3435 R/day is real and it is worth re-visiting when")
w("> the sample supports it — `n` is 85 on RECORDED with 3 evaluable folds. What would change the")
w("> answer is sample, not a repair on this axis.")
w("")

# =====================================================================================
w("## 3. Seal membership — the H1/R2 answer, across all three mechanisms")
w("")
w(f"{MB['why_three_mechanisms']}")
w("")
w("| file | R2 `input_bindings` | R1 `input_bindings` | `code_authority_paths` "
  f"({MB['n_code_authority_paths']} entries) | `config_file_hashes` | **sealed?** |")
w("|---|---|---|---|---|---|")
for f, r in MB["per_file"].items():
    w(f"| `{f}` | {r['R2_input_binding'] or '—'} | {r['R1_input_binding'] or '—'} | "
      f"{'YES' if r['in_code_authority_paths'] else '—'} | "
      f"{'YES' if r['in_config_file_hashes'] else '—'} | "
      f"{'**SEALED**' if r['sealed_by'] else 'unbound'} |")
w("")
w("> **The answer, plainly: NEITHER change ends the parked B7.5 campaign option.**")
w("> `execution_packets.py` and `market_expansion_d1.py` are bound by **none** of the three")
w("> mechanisms — not R2's 43 input bindings, not the runner's")
w(f"> {MB['n_code_authority_paths']} `code_authority_paths`, and not the two files in")
w("> `config_file_hashes` that feed `shared_execution_contract_digest_sha256`. There is no owner")
w("> question to route here.")
w("")
w("For contrast, and because these are the files a careless diff would reach for: "
  "`config/agent_config.yaml`, `config/profiles/operator_profile.yaml` and "
  "`src/components/exit_policy_v4.py` **are** sealed, each by two or three mechanisms. "
  "`config/profiles/redacted_account.yaml` is bound by neither contract — but it carries live authority "
  "and the redacted_account token binds its bytes, so it is untouchable for a different reason.")
w("")

# =====================================================================================
w("## 4. Token implications")
w("")
w(f"**{TK['verdict']}**")
w("")
w(f"Verified: {TK['verified_by']}")
w("")
w(f"**But:** {TK['but']}")
w("")

# =====================================================================================
w("## 5. Test plan")
w("")
w("Per change, and none of it needs market data:")
w("")
w("| # | test | what it pins |")
w("|---|---|---|")
w("| 1 | drive `build_book_trade_params` for the changed sleeve and assert the resolved "
  "`final_target_r` **and** `take_profit_1` | that the edit is not a no-op — the single failure "
  "mode this dossier exists to prevent |")
w("| 2 | assert `final_from_intent` is absent from the changed `mx_btcusd` profile, by name | "
  "that a later edit cannot silently re-introduce the no-op |")
w("| 3 | blast-radius snapshot: resolve every registered sleeve before and after and assert "
  "exactly the named sleeve moved | that the change has no unnamed reach |")
w("| 4 | assert every ARMED sleeve's resolved params are byte-identical across the change "
  "(for `mx_btcusd`) | that live money does not move |")
w("| 5 | assert the three fail-closed live gates still pass for the changed sleeve "
  "(`.tools/probe_per_sleeve_exit_gates.py` is the precedent) | that the packet is still placeable |")
w("| 6 | a coverage test that fails if a sleeve is added without a snapshot row | that test 3 "
  "cannot silently stop covering the registry — AQ's `test_time_stop_units.py` pattern |")
w("")
w("`tests/ultimate_book/test_exit_contract_activation.py` in this session implements 1–4 and 6 "
  "against BOTH candidate diffs, applied in memory — so the tests exist and pass **before** any "
  "spec byte moves, which is the only order in which test 1 can prove anything.")
w("")

# =====================================================================================
w("## 6. Rollback")
w("")
w("| | `mx_btcusd` | `sub_xvol_pullback` |")
w("|---|---|---|")
w("| **revert** | delete the added `SLEEVE_EXIT_PROFILES[...]` entry; the cohort comprehension "
  "at `:144-148` restores the 2R/`final_from_intent` default | restore `final_target_r=3.0` |")
w("| **blast radius of the revert** | 1 sleeve, 0 armed | 1 sleeve, 1 armed |")
w("| **token** | none — no config byte moves either way | none |")
w("| **seal** | none — the file is unbound by all three mechanisms | none |")
w("| **open positions** | a position opened under 5R keeps the **broker-side TP set at entry** "
  "(`execution.py:3488`), so a revert does not move an open trade's target — it changes the next "
  "entry only | same |")
w("| **host** | the revert is a deploy, i.e. the carry ceremony again. Reverting in this repo "
  "alone changes nothing live. | same |")
w("")
w("> The asymmetry worth naming: **landing is a deploy and reverting is a deploy.** Neither change")
w("> can be undone by flipping a flag, because there is no flag — the contract is code. If a")
w("> reversible form is wanted, that is a different design (a config-keyed target), and it would")
w("> put the value in a file that IS sealed and IS token-bound. The unbound-code form is the")
w("> cheaper one and this dossier recommends it.")
w("")

# =====================================================================================
w("## 7. The sizing basis for `mx_btcusd`, per the ratified population rule")
w("")
w(f"Cell: `{SZ['cell']['sleeve']}` @ `{SZ['cell']['exit']}`, population `{SZ['cell']['population']}`, "
  f"band `{SZ['cell']['band']}`, option `{SZ['cell']['option']}` — verdict **{SZ['cell']['verdict']}**, "
  f"p_raw {SZ['cell']['p_raw']:.10f}. Fold rule `{SZ['cell']['fold_rule']}`.")
w("")
w("| fold | OOS window | n | disputed | gross R/trade | **fold R/day** |")
w("|---:|---|---:|---:|---:|---:|")
for f in SZ["fold_table"]:
    w(f"| {f['fold_id']} | {f['oos_start']} … {f['oos_end']} | {f['n_trades']} | "
      f"{f['n_disputed']} | {f['gross_r_per_trade']} | {f['fold_mean_r_per_day']:.4f} |")
w("")
w(f"> **Size on {SZ['recent_two_fold_mean_r_per_day']:.4f} R/day, not on the pooled")
w(f"> {SZ['pooled_oos_mean_r']:.4f}.** The recent two folds average")
w(f"> {SZ['recent_two_fold_mean_r_per_day']:.4f} against the first three's")
w(f"> {SZ['early_folds_mean_r_per_day']:.4f} — **{SZ['decay_ratio']:.1%}**, on")
w(f"> {SZ['n_trades_in_the_recent_two_folds']} of {SZ['n_trades_total']} OOS trades and the most")
w("> recent 2.7 years. Every gate passes anyway, because `stability` counts the **sign** of a fold")
w("> mean and not its level, so a 7.6× chronological decay reads as 5/5 positive by construction.")
w("")
fb = SZ["family_bill_now"]
w("**And the bill has moved since the admission was ratified.** p is family-invariant; only the bar")
w("moves:")
w("")
w("| declared family | size | BH rank-1 bar at α = 0.10 | p is inside by |")
w("|---|---:|---:|---:|")
w(f"| V3, at ratification | {fb['declared_family_at_ratification_V3']} | "
  f"{fb['bh_rank1_bar_at_V3']:.7f} | {fb['inside_by_at_V3']:.2f}× |")
w(f"| **V5, now** | **{fb['declared_family_now_V5']}** | {fb['bh_rank1_bar_at_V5']:.7f} | "
  f"**{fb['inside_by_at_V5']:.2f}×** |")
w("")
w(f"**Still admits at the current family: {fb['still_admits_at_V5']}.** The wave-11 ratchet raised")
w(f"`CANDIDATE_BOOK_V1` from {fb['declared_family_at_ratification_V3']} to "
  f"{fb['declared_family_now_V5']} and the admission survives it, with less headroom.")
w("")

# =====================================================================================
w("## 8. What each change still needs before it reaches the owner")
w("")
w("**`mx_btcusd @ target_5R` — one hard precondition, and it is not a research question.**")
w("After AQ's time-stop repair an open `mx_*` position requests **7,744** M15 bars per tick. If the")
w("terminal returns fewer than 7,680 closed M15 bars, the printed-bar count can never reach the")
w("budget and **the time stop never fires at all** — the wall-clock fallback does not catch it,")
w("because that path needs a `None` return and not an honestly short count. The backstop degrades to")
w("**inert**, not late. Nothing armed is exposed today (the five live sleeves are H4 at 1280, want")
w("1344). **Measure the terminal's `copy_rates` ceiling before arming anything in this cohort** —")
w("it is `F15` on the fleet map, the cheapest item there, and it is a precondition rather than a")
w("nice-to-have.")
w("")
w("Beyond that: registry confidence is 0.025, so admitting the sleeve into the funded book is")
w("**economically inert** (~0.136 %/month) — re-weighting is a separate owner decision (OD-AI-5),")
w("and the eligibility-vs-allocation distinction in `MX_BTCUSD_CHALLENGE_DOSSIER.md` §6 stands.")
w("")
w("**`sub_xvol_pullback @ target_4R` — sample.** It is a REJECT at every band at the ratified rule,")
w("3.8× outside the rank-1 bar, on 85 trades and 3 evaluable folds. Nothing about the change is")
w("wrong; there is simply not enough of it. Re-visit when `n` supports it, and until then the armed")
w("sleeve keeps the 3R contract its own walk baseline reproduces exactly.")
w("")

w("## 9. Provenance")
w("")
w("| claim | where |")
w("|---|---|")
w("| the no-op proof, all four profile states | `AS_EXIT_CONTRACT_ACTIVATION_V1.json` → `noop` |")
w("| every blast radius | same → `blast` (measured by resolving all "
  f"{BL['mx_btcusd_profile_route']['n_sleeves_in_registry']} registered sleeves before and after) |")
w("| seal membership, three mechanisms | same → `membership` |")
w("| token | same → `token` |")
w("| the re-gate, the control, carry and maxbars | same → `regate` (48 arms, "
  "trial-ledgered as `xvol_exit_regate`) |")
w("| the sizing basis and the family bill | same → `sizing`; folds from "
  "`phase10/receipts/POPULATION_RULE_V1.json` → `admission_fold_structure` |")
w("| AK's published cell | `phase8/receipts/AK_EXIT_FRONTIER_V2.json` → "
  "`sleeves.sub_xvol_pullback` |")
w("| the admission itself | `phase11/MX_BTCUSD_CHALLENGE_DOSSIER.md` and "
  "`phase11/receipts/AQ_CONTRACT_TRUTH_V1.json` |")

OUT.write_text("\n".join(x for x in L if x is not None) + "\n")
print(f"wrote {OUT.relative_to(REPO)}  ({len(L)} lines)")
