#!/usr/bin/env python3
"""Generate `phase11/FIVE_SLEEVE_OPERATOR_PAGE.md` from the committed AS-1 artifacts.

Every figure on the page is read out of a JSON artifact and the artifact path is stamped in the
provenance table. If an input moves, this generator dies rather than printing a stale number — the
same rule `aq_btc_dossier.py` runs under, and for the same reason: an operator page with a number
nobody can reproduce is worse than no page.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
AUDIT = ROOT / "docs/audits/fable5-vision-audit-20260725"
R = AUDIT / "phase11/receipts"
OUT = AUDIT / "phase11/FIVE_SLEEVE_OPERATOR_PAGE.md"

BASIS = json.loads((R / "AS_LIVE_SLEEVE_BASIS_V1.json").read_text())
CONDS = json.loads((R / "FIVE_SLEEVE_STOP_CONDITIONS_V1.json").read_text())

ARMED = tuple(BASIS["armed_tags"])
C = CONDS["conditions"]
FLOORS = C["S1a_risk_floor"]["per_sleeve_account"]
EVID = C["S1b_evidence_floor"]["per_sleeve_account"]
CARRY = C["S3_carry_surprise"]["per_sleeve_account"]
HOLD = C["S4_hold_time_surprise"]["per_sleeve"]
CONTRACT = BASIS["live_contract"]
CB = BASIS["carry_basis"]
PRIOR = BASIS["live_prior"]["per_sleeve_account"]
SIG = BASIS["live_prior_significance"]["per_sleeve_account"]


def need(value, what):
    if value is None:
        raise SystemExit(f"missing input: {what} — refusing to print a page with a hole in it")
    return value


def f(x, nd=4, sign=True):
    if x is None:
        return "—"
    return f"{x:+.{nd}f}" if sign else f"{x:.{nd}f}"


L: list[str] = []
w = L.append

w("# The armed FIVE-sleeve book — the operator page")
w("")
w("**For Borhen. You are the monitor.** Nothing on this page stops trading, changes size, or")
w("touches a gate. Every check is a message to you, and the two decisions it can ever ask for —")
w("take a sleeve off, or leave it on — are yours.")
w("")
w(f"Generated by `phase11/receipts/as_operator_page.py` from committed artifacts. Armed set read")
w(f"from `{BASIS['armed_set_provenance']['receipt']}` (host commit")
w(f"`{BASIS['armed_set_provenance']['host_commit']}`), asserted verbatim — this page cannot be the")
w("source of truth for what is armed.")
w("")
w("---")
w("")

# --------------------------------------------------------------------------
w("## 0. Read this before anything else")
w("")
w("**Two of the five sleeves were armed on your explicit risk acceptance, not on a passed gate.**")
w("`fx_jpy` and `sub_mid_dn_revert` joined the book on 2026-07-30. Neither has passed an admission")
w("standard on any population. That was a decision you made with the price in front of you")
w("(P2 `p_pass` 0.9172 → 0.8915 for 4.501 → 6.120 %/month at measured p99), and this page does not")
w("re-litigate it. What it does is the half that was missing: **a pre-registered exit.** A risk")
w("acceptance without one is not a decision, it is a hope.")
w("")
w("The stop conditions below were written **before the first post-arming fill existed**, so they")
w("cannot have been chosen to fit it. They are in")
w("`phase11/receipts/FIVE_SLEEVE_STOP_CONDITIONS_V1.json`, and the tool that evaluates them cannot")
w("act on them.")
w("")
w("**One thing to have in your head about the two new sleeves, and it is the whole risk story:**")
ftmo_fx, fn_fx = FLOORS["FTMO::fx_jpy"], FLOORS["redacted_account::fx_jpy"]
w("")
w(f"> `fx_jpy`'s archive net expectancy at its own **measured** carry is")
w(f"> **{f(ftmo_fx['archive_net_r_per_trade_at_measured_carry'], 5)} R/trade on FTMO** and")
w(f"> **{f(fn_fx['archive_net_r_per_trade_at_measured_carry'], 5)} on redacted_account** — near zero. At")
w(f"> that rate it needs **{ftmo_fx['fills_to_trip_at_archive_expectancy']} fills** (FTMO) to earn")
w(f"> back the {abs(ftmo_fx['cumulative_net_r_floor']):.1f} R floor it would reach in")
w(f"> **{ftmo_fx['fills_to_trip_at_live_prior']} fills** at the rate its own 21 live fills ran at.")
w(f"> On redacted_account that asymmetry is {fn_fx['fills_to_trip_at_archive_expectancy']} against")
w(f"> {fn_fx['fills_to_trip_at_live_prior']}. **The sleeve is roughly 20× faster to the downside")
w("> bound than to the upside one.** That is not a prediction; it is the arithmetic of arming a")
w("> near-zero-expectancy sleeve, and it is why `fx_jpy` gets the tightest floor in the book.")
w("")
w("`sub_mid_dn_revert` is a different case: its archive net expectancy is")
w(f"**{f(FLOORS['FTMO::sub_mid_dn_revert']['archive_net_r_per_trade_at_measured_carry'], 5)} R/trade**")
w("— real but modest — and it has **zero** live fills ever, on either account, because the config")
w("could not generate it until `include_clean3` went true. Its BUILT population was also re-derived")
w("this wave (AQ-3, 503 → 533 trades on the repaired session clock), so treat any published figure")
w("for it as provisional until the four stale downstream artifacts are rebuilt.")
w("")

# --------------------------------------------------------------------------
w("## 1. The armed set, and what each sleeve was armed on")
w("")
w("| sleeve | conf | live exit policy | target | time stop | archive net R/trade at measured carry | live fills ever |")
w("|---|---:|---|---:|---|---:|---:|")
for tag in ARMED:
    c, fl = CONTRACT[tag], FLOORS[f"FTMO::{tag}"]
    own = need(c["time_stop_own_bars"], f"{tag} time_stop_own_bars")
    nfills = sum((PRIOR.get(f"{a}::{tag}") or {}).get("n_fills", 0)
                 for a in ("FTMO", "redacted_account"))
    ts = f"{c['time_stop_bars_m15']} M15 printed = {own:.0f} of 80 own bars ({c['decision_grid']})"
    w(f"| `{tag}` | {c['registry_confidence']} | `{c['policy']}` | "
      f"{c['final_target_r']}R | {ts} | "
      f"{f(fl['archive_net_r_per_trade_at_measured_carry'], 5)} | {nfills} |")
w("")
w("**The contract-fidelity answer, which is the good news on this page:** all five armed sleeves'")
w("live time stops are **unit-correct**, and none is in the `mx_*` cohort whose time stop was the")
w("conversion ratio.")
w("")
w("Four of the five declare 1280 printed M15 bars, and for these symbols that is **80 of their own")
w("bars — the research `maxbars`**, so the stop can only bind where the walk already truncated.")
w("**That identity is MEASURED, not definitional**, and the distinction is the same unit trap AQ")
w("caught: the calendar ratio and the printed-bar ratio are different quantities and they coincide")
w("here only because these symbols happen to print 16 M15 bars per H4 bar. Session AD measured it")
w("(`AD_TIMESTOP_UNITS_V1.json` → `m15_per_own_bar_trade_weighted` = 16.0 for `crypto`,")
w("`energy_agri`, `sub_xvol_pullback`, `sub_mid_dn_revert`). It does **not** hold estate-wide — the")
w("same field reads 92 rather than 96 for `mx_ger40`, `mx_jp225` and the `mx_us*` sleeves.")
w("")
w("`fx_jpy` is the one exception in the armed set — 48 of 80 own bars, tighter than research — and")
w("the measured cost is")
w(f"**{CONTRACT['fx_jpy']['frac_trades_the_time_stop_would_truncate']:.1%} of walked trades**.")
w("")
w("> **Two honest qualifications on that 0.2 %, both from an adversarial pass.** It is a **trade**")
w("> count, and the R-weighted figure is about 20× larger — the truncated trades are among the")
w("> sleeve's best, on the armed sleeve with the thinnest expectancy, so 'immaterial' is a fair")
w("> word for the trade count and a generous one for the economics. And the number is **AD's**")
w("> wave-7 measurement carried forward: AQ's contract-truth driver loads AD's `sleeve_contracts`")
w("> verbatim, so 'AQ measured' — which this page said in a first cut — is a misattribution.")
w("")
w("**And the one thing on that table worth watching.** `energy_agri` is the only armed sleeve whose")
w("live exit policy is a `partial_be_runner`, and AD measured that scale-out at **−0.308 R/day**")
w("against the plain exit on n=67. Thin, and a question rather than a recommendation — but it is a")
w("live contract feature on armed money with a negative measurement against it.")
w("")

# --------------------------------------------------------------------------
w("## 2. The stop conditions")
w("")
w("Six conditions plus the unchecked rule. Each one names the class it belongs to, because a")
w("risk bound and an inference are different things and conflating them is how you either ignore a")
w("real loss or kill a sleeve on noise.")
w("")
w("| id | class | what trips it | what to do |")
w("|---|---|---|---|")
for cid in ("S6_book_composition", "S1a_risk_floor", "S1b_evidence_floor",
            "S2_gross_negative",
            "S3_carry_surprise", "S4_hold_time_surprise", "S5_stop_out_run", "S7_unchecked"):
    blk = C[cid]
    w(f"| **{cid.split('_')[0]}** | {blk['class']} | {blk['what']} | {blk['action']} |")
w("")

w("### S1 — TWO floors, because one number cannot answer two questions")
w("")
w("This page had **one** floor in its first cut, `-max(3.0, 12 × |archive net expectancy|)`,")
w("justified by a claim about its false-alarm rate that had never been computed. Computing it")
w("**refuted the claim**, and the refutation is worth more than the original number:")
w("")
w("| account · sleeve | archive net R/trade | **risk floor** | how often it fires on a HEALTHY sleeve | **evidence floor** | its false-alarm rate |")
w("|---|---:|---:|---:|---:|---:|")
for acct in ("FTMO", "redacted_account"):
    for tag in ARMED:
        r, e = FLOORS[f"{acct}::{tag}"], EVID[f"{acct}::{tag}"]
        fp = r.get("measured_false_trip_probability_within_60_fills")
        w(f"| {acct} · `{tag}` | {f(r['archive_net_r_per_trade_at_measured_carry'], 5)} | "
          f"{r['cumulative_net_r_floor']:.2f} R | "
          f"{('**' + format(fp, '.0%') + '**') if (fp is not None and fp > 0.15) else format(fp, '.1%')} | "
          f"{e['evidence_floor_r']:.2f} R | "
          f"{e['measured_false_trip_probability_within_60_fills']:.1%} |")
w("")
w("**Read the third column.** On `fx_jpy` the −3.00 R floor fires **74–77 % of the time on a")
w("sleeve running at exactly its own archive expectancy.** On `sub_mid_dn_revert` it is 58 %, on")
w("`energy_agri` 35–38 %. Those are not tripwires; they are coin flips wearing a threshold's")
w("clothes — and I only found that out by computing the number I had already claimed.")
w("")
w("**Why, and it is structural rather than a bad choice of constant.** `fx_jpy`'s expectancy is")
w(f"+{FLOORS['FTMO::fx_jpy']['archive_net_r_per_trade_at_measured_carry']:.5f} R/trade against a")
w(f"per-trade dispersion of {EVID['FTMO::fx_jpy']['archive_r_dispersion_sd']:.3f} R. A")
w("near-zero-drift random walk with that step size passes −3 R almost surely. **There is no")
w("threshold on that sleeve that is both tight and sound**, and pretending otherwise would have")
w("been the worst thing on this page.")
w("")
w("So both floors are published and each answers its own question:")
w("")
w("- **the risk floor** is *what you pre-registered as the price of finding out*. It is a")
w("  statement of your tolerance and it is a perfectly good one. When it fires, the tool now says")
w("  on the same line how often it fires on a healthy sleeve, so nobody reads it as evidence.")
w("- **the evidence floor** is *the depth at which a trip means something*: the deepest 0.5 R step")
w(f"  whose false-alarm rate is ≤ {C['S1b_evidence_floor']['method']['target_false_trip_rate']:.0%}")
w(f"  over {C['S1b_evidence_floor']['method']['horizon_fills']} fills, by bootstrap over each")
w("  sleeve's **own** centred archive R distribution — measured, not assumed normal, because these")
w("  distributions have a stop-out mass at −1 R and a long right tail and a normal approximation")
w("  understates the left tail exactly where this question lives.")
w("")
w("On `crypto` and `sub_xvol_pullback` the two coincide: their expectancy dwarfs their dispersion,")
w("so the risk floor was already safe. **The gap only opens on the sleeves that were armed without")
w("a passed gate**, which is not a coincidence.")
w("")
w("| account · sleeve | fills to earn the risk floor back at the archive rate | fills to reach it at the live prior |")
w("|---|---:|---:|")
for acct in ("FTMO", "redacted_account"):
    for tag in ARMED:
        r = FLOORS[f"{acct}::{tag}"]
        w(f"| {acct} · `{tag}` | {r['fills_to_trip_at_archive_expectancy'] or '—'} | "
          f"{r['fills_to_trip_at_live_prior'] or '— (no live record)'} |")
w("")

w("### S2 — negative GROSS, and the repair the live record forced")
w("")
w("A sleeve losing before any cost is charged cannot be rescued by a better cost model. That is")
w("what the two dead JPY sleeves looked like and it took a fortnight to see. But the tripwire now")
w("requires the loss on **both** weightings, and here is why:")
w("")
ff = PRIOR["FTMO::fx_jpy"]
w(f"> `fx_jpy`'s {ff['n_fills']} FTMO fills read **{f(ff['gross_r_per_fill_trade_weighted'])} R/fill**")
w(f"> trade-weighted and **{f(ff['gross_r_per_fill_day_weighted'])}** day-weighted — a")
w(f"> {abs(1 - ff['gross_r_per_fill_day_weighted'] / ff['gross_r_per_fill_trade_weighted']):.0%}")
w("> attenuation on the same fills, because the losing days carry up to four fills and the winning")
w("> days carry one. The decision day is the dependence unit (Session R measured lag-1 rho 0.511),")
w("> so a trade-weighted-only tripwire reports a sleeve's *worst* reading as its verdict.")
w("")
w("It also computes both weightings **per account**. Pooling the two accounts into one day block")
w("mixes two independent books and flips the pooled day-weighted figure positive (+0.0563), which is")
w("an artifact of the pooling and not a property of either account. This page had that wrong in a")
w("first cut and the per-account split is what corrected it.")
w("")

w("### S3 — carry, where two sleeves have no room at all")
w("")
w("| account · sleeve | measured p90 nights | break-even nights | alert above | stop above |")
w("|---|---:|---:|---:|---:|")
for acct in ("FTMO", "redacted_account"):
    for tag in ARMED:
        r = CARRY[f"{acct}::{tag}"]
        w(f"| {acct} · `{tag}` | {r['measured_nights_p90']} | "
          f"{r['break_even_nights']:.3f} | {r['alert_mean_nights_above']} | "
          f"{r['stop_mean_nights_above']:.3f} |")
w("")
w("**`fx_jpy` is a zero-carry sleeve and its break-even says so:**")
w(f"**{CARRY['FTMO::fx_jpy']['break_even_nights']:.3f} nights on FTMO and")
w(f"{CARRY['redacted_account::fx_jpy']['break_even_nights']:.3f} on redacted_account.** Its archive p90 is zero")
w("nights and the broker charged swap on **0 of its 32 live positions**. So a stop threshold that")
w("reads as impossibly tight is not a tight threshold — it is the sleeve's own arithmetic. One")
w("night of carry on one trade in twenty ends the redacted_account edge.")
w("")

# --------------------------------------------------------------------------
w("## 3. The pre-arming prior — what you already knew when you accepted the risk")
w("")
w("**This is never merged into a stop-condition evaluation.** It is reported beside them because")
w("`fx_jpy` is the only armed sleeve with any live record at all, and reading that record correctly")
w("is the difference between a decision and a reflex.")
w("")
w("| account · sleeve | n | day blocks | gross R/fill trade-wt | gross R/fill day-wt | net R total | net R/day | closes |")
w("|---|---:|---:|---:|---:|---:|---:|---|")
for key, blk in PRIOR.items():
    if not blk.get("n_fills"):
        continue
    acct, tag = key.split("::")
    w(f"| {acct} · `{tag}` | {blk['n_fills']} | {blk['n_day_blocks']} | "
      f"{f(blk['gross_r_per_fill_trade_weighted'])} | {f(blk['gross_r_per_fill_day_weighted'])} | "
      f"{f(blk['net_r_total'], 3)} R | {f(blk['net_r_per_day'])} | "
      f"{blk['close_reasons']} |")
w("")
w("And the honest reading, which is not the one the totals suggest:")
w("")
w("| account | p vs zero | p vs the archive gross it was armed on | blocks | resolution floor |")
w("|---|---:|---:|---:|---:|")
for key, s in SIG.items():
    acct = key.split("::")[0]
    z, a = s["vs_zero"], s["vs_archive_gross"]
    w(f"| {acct} · `{key.split('::')[1]}` | {z['p']:.4f} | {a['p']:.4f} | {z['n_blocks']} | "
      f"{z['resolution_floor']:.2e} |")
w("")
w("> **The loss is real and it is not significant.** −13.949 R net across both accounts is money")
w("> that left the accounts. On an exact day-blocked sign-flip it is distinguishable neither from")
w("> zero (p 0.37 / 0.40) nor from the archive gross the sleeve was armed on (p 0.16 / 0.22). Thirty-")
w("> two fills over thirteen days cannot establish an edge in either direction. **That is precisely")
w("> why the stop conditions above are risk bounds rather than tests** — they bound what you pay to")
w("> find out, and they make no claim to have found out.")
w("")
w("One more fact about those fills worth having: **the live time stop never bound.** Longest hold")
w(f"was {PRIOR['FTMO::fx_jpy']['max_hold_hours']:.2f} h against a 12-trading-hour stop, and")
w("24 of 32 closed at the stop loss. The sleeve's problem is entry, not exit — which is what the")
w("expansion receipt meant by *\"its blocker moved to the entry side\"*, and AQ's hour-01 work")
w("(+0.111 R/trade net vs hour 00) is the standing repair on that axis.")
w("")

# --------------------------------------------------------------------------
w("## 4. One command")
w("")
w("```bash")
w("python3 scripts/book_sleeve_telemetry.py \\")
w("    --fills <dir>/LIVE_TRADE_ROWS.jsonl \\")
w(f"    --armed-utc {BASIS['armed_utc']['FTMO']} \\")
w(f"    --launch-tags-ftmo {','.join(ARMED)} \\")
w(f"    --launch-tags-redacted_account {','.join(ARMED)}")
w("```")
w("")
w("Everything is optional except that without `--fills` nothing economic evaluates. **There is no")
w("live feed.** The file is built from a read-only VPS export:")
w("")
w("```bash")
w("# 1. export the VPS's MT5 API state (read-only; the orchestrator's ceremony)")
w("#    -> <export>/09_mt5_api/{ftmo,redacted_account}_history_{deals,orders}_get.jsonl")
w("# 2. turn it into priced trade rows")
w("python3 scripts/w7_live_forensics.py --export-root <export> --out-dir <dir>")
w("#    -> <dir>/LIVE_TRADE_ROWS.jsonl        <- the --fills file")
w("```")
w("")
w("So the economic conditions are only as fresh as the last export. **Until one exists with")
w("post-arming fills in it, the page says so and exits 3, not 0** — 'nothing is wrong' and 'nothing")
w("was checked' are different, and collapsing them is how `.tools/monitor_books.py` sat mute through")
w("the window it was meant to be watching.")
w("")
w("Exit codes: `0` clean · `1` a STOP or an ALERT · `3` clean, but something could not be checked.")
w("")
w("Run it **when you look**, not on a timer. Expect ~7 book-days a month; long silences are normal.")
w("")
w("This page complements `phase4/CANARY_OPERATOR_PAGE.md` rather than replacing it: that one answers")
w("*is it armed, is it alive, what is the headroom, is the cost model still right*. This one answers")
w("*what is each of the five sleeves actually doing, and has any of them reached the line*.")
w("")

# --------------------------------------------------------------------------
d = CONDS["de_arm_mechanism"]
w("## 5. If you decide to take a sleeve back off")
w("")
w(f"**How.** {d['how']}")
w("")
w(f"**What it stops.** {d['what_it_stops']}")
w("")
w(f"**What it does NOT stop — and this is the half that matters.** {d['what_it_does_NOT_stop']}")
w("")
w(f"**The same-day size consequence.** {d['same_day_size_consequence']}")
w("")
w(f"**Never.** {d['never']}")
w("")
w("Two `--tags` failure modes to know before the ceremony, both already measured: `--tags \"\"` is")
w("falsy at `run_book.py:340` and silently means **all BUILT sleeves** — fail-open; and an all-typo")
w("`--tags` yields an empty spec list and the book stands down silently every tick")
w("(`registry.py:144`) — fail-closed, but mute. That is why S6 is the first check on the page and")
w("why nothing below it means anything if it is red.")
w("")

# --------------------------------------------------------------------------
w("## 6. Provenance")
w("")
w("| claim | artifact |")
w("|---|---|")
w("| the armed set | `phase8/receipts/FIVE_SLEEVE_EXPANSION_20260730.md` "
  f"(sha256 `{BASIS['armed_set_provenance']['sha256'][:12]}…`) |")
w("| the live exit contract of each armed sleeve | "
  "`src/components/ultimate_book/execution_packets.py::SLEEVE_EXIT_PROFILES`, read at generation |")
w("| the contract-fidelity class and truncation fraction | "
  "`phase11/receipts/AQ_CONTRACT_TRUTH_V1.json` → `spec_audit.sleeves` |")
w("| archive gross, cost, swap per night, break-even nights, measured nights | "
  "`phase7/receipts/AD_CARRY_TIERS_RESTATED_V1.json` |")
w("| the live-fill prior | "
  f"`phase1/w7_forensics/LIVE_TRADE_ROWS.jsonl` (sha256 "
  f"`{BASIS['live_prior']['source_sha256'][:12]}…`, {BASIS['live_prior']['n_rows_in_corpus']} rows) |")
w("| the derived floors and every threshold | "
  "`phase11/receipts/FIVE_SLEEVE_STOP_CONDITIONS_V1.json` |")
w("| the basis for all of the above | `phase11/receipts/AS_LIVE_SLEEVE_BASIS_V1.json` |")
w("| the evaluator, and the tests that pin its behaviour | "
  "`scripts/book_sleeve_telemetry.py`, `tests/ultimate_book/test_book_sleeve_telemetry.py` |")
w("")
w("Nothing on this page was transcribed. `as_operator_page.py` reads every figure from the")
w("artifacts above and refuses to write if one is missing.")

OUT.write_text("\n".join(L) + "\n")
print(f"wrote {OUT.relative_to(ROOT)}  ({len(L)} lines)")
sys.exit(0)
