# Generated by scripts/build_science_goal_program.py
$ErrorActionPreference = 'Stop'
$Repo = "C:\Users\MSI\Documents\ai-trading-agent"
$Root = "C:\tmp\gtosg"
New-Item -ItemType Directory -Path $Root -Force | Out-Null

# G0 Program Governor
git -C $Repo worktree add -b science-goals/g0-program-governor "C:\tmp\gtosg\G0" main
# G1 Validation Probability Statistics Causality
git -C $Repo worktree add -b science-goals/g1-validation-statistics "C:\tmp\gtosg\G1" main
# G2 Stochastic Processes Time Series Tails
git -C $Repo worktree add -b science-goals/g2-stochastic-tails "C:\tmp\gtosg\G2" main
# G3 Geometry Fractals Signal Processing
git -C $Repo worktree add -b science-goals/g3-geometry-signal "C:\tmp\gtosg\G3" main
# G4 Market Microstructure Order Book Auction
git -C $Repo worktree add -b science-goals/g4-microstructure-auction "C:\tmp\gtosg\G4" main
# G5 Behavioral Finance Psychology Game Theory
git -C $Repo worktree add -b science-goals/g5-behavioral-game "C:\tmp\gtosg\G5" main
# G6 Momentum Continuation Breakout Mean Reversion
git -C $Repo worktree add -b science-goals/g6-momentum-reversion "C:\tmp\gtosg\G6" main
# G7 Macro Cross Asset Rates FX Gold
git -C $Repo worktree add -b science-goals/g7-macro-cross-asset "C:\tmp\gtosg\G7" main
# G8 Options Gamma Volatility Risk Premium
git -C $Repo worktree add -b science-goals/g8-options-vol "C:\tmp\gtosg\G8" main
# G9 AI ML RL LLM Trading Systems
git -C $Repo worktree add -b science-goals/g9-ai-ml-systems "C:\tmp\gtosg\G9" main
# G10 Execution Entries Exits Risk Portfolio
git -C $Repo worktree add -b science-goals/g10-execution-risk "C:\tmp\gtosg\G10" main
# G11 Data Sources And Market Expansion
git -C $Repo worktree add -b science-goals/g11-data-sources-expansion "C:\tmp\gtosg\G11" main
# G12 Red Team Leakage Source Validity
git -C $Repo worktree add -b science-goals/g12-red-team "C:\tmp\gtosg\G12" main
