#!/usr/bin/env python3
"""Is the book abnormally quiet? A message to the operator, calibrated, and nothing else.

    python3 scripts/book_silence_check.py --account FTMO --last-fill 2026-07-10
    python3 scripts/book_silence_check.py --account redacted_account --last-fill 2026-07-10 --json

WHY THIS EXISTS
---------------
`OD3_DOSSIER_SURVIVOR_BOOK.md` §6 names the armed book's realistic failure mode: *"a book
that does not trade enough to matter"*. `CANARY_OPERATOR_PAGE.md` tells the operator that
"long silences are normal, not a fault" — which is true and unactionable, because until
Session BB measured it nobody knew how long normal is. A fixed rule ("no trade in a week =>
something is wrong") on a book at this density fires roughly every three weeks by
construction; a rule set too loose never fires at all.

So the threshold is measured rather than chosen, and this file is the mechanism that makes
the measurement usable. It is a **message**, exactly in the canary page's sense: it stops
nothing, sizes nothing and touches no gate. There is no broker call in this file and no
import that could make one.

WHAT IT COUNTS, AND THE ONE THING THAT MAKES IT HONEST
--------------------------------------------------------
**Weekday sessions, not calendar days.** A weekend is not evidence of anything. A rule
counting calendar days fires 40 % sooner over a long weekend than over a mid-week run of the
same market silence, which is a false alarm generated by the calendar rather than by the
book. `BB_FILL_TRUTH_V1.json -> quiet_alarm` is measured on the same axis, so the thresholds
and this counter agree by construction.

WHAT IT CANNOT TELL YOU
-----------------------
Whether the engine is alive. A dead worker and a quiet market produce the identical signal
here, and no amount of statistics on the fill series can separate them — that is the
heartbeat's job (`scripts/run_book_supervisor.ps1`, the canary page's process checks).
This answers only: *given that the book is running, is this silence longer than the archive
says it should be?* The distinction is printed on every run so it cannot be forgotten.

THRESHOLD PROVENANCE
--------------------
Read from `CH_QUIET_BOOK_THRESHOLDS_V1.json` at run time, never transcribed, so a re-measurement
propagates without an edit here. If the receipt is absent the tool refuses rather than
falling back to a literal: a hard-coded threshold whose provenance nobody can check is the
thing this file exists to replace.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path
from typing import Iterable

REPO = Path(__file__).resolve().parents[1]
RECEIPT = (REPO / "docs/audits/fable5-vision-audit-20260725/phase15/receipts"
           / "CH_QUIET_BOOK_THRESHOLDS_V1.json")

OK, WARN, ALERT = "OK", "WARN", "ALERT"


def weekday_sessions_between(a: dt.date, b: dt.date) -> int:
    """Mon-Fri days strictly after `a` and up to and including `b`. 0 if b <= a.

    Strictly after, because the day of the last fill is not silence.
    """
    if b <= a:
        return 0
    n, d = 0, a + dt.timedelta(days=1)
    while d <= b:
        if d.weekday() < 5:
            n += 1
        d += dt.timedelta(days=1)
    return n


def load_thresholds(account: str, path: Path | None = None) -> dict:
    if not account:
        raise SystemExit("--account is required: quiet thresholds are per account")
    p = path or RECEIPT
    if not p.is_file():
        raise SystemExit(
            f"threshold receipt not found at {p}. This tool reads its thresholds from the "
            f"measurement rather than carrying a literal; regenerate it with "
            f"`python3 docs/audits/fable5-vision-audit-20260725/phase15/receipts/"
            f"ch_lever_measurements.py --stage quiet`.")
    doc = json.loads(p.read_text())
    if doc.get("schema") == "gtos.live.quiet_basis.v1":
        rec = ((doc.get("book_level") or {}).get(account)) or {}
        warn = rec.get("warn_after_silent_weekday_sessions")
        alert = rec.get("alert_after_silent_weekday_sessions")
        false = rec.get("expected_false_alarms_per_year")
        density = rec.get("book_day_density")
        window = rec.get("measured_window")
        armed = rec.get("armed_set")
    else:
        # Backward-compatible explicit override for BB's pre-mx, single-book receipt. The
        # current default never takes this branch; it exists for historical reproductions.
        rec = (doc.get("quiet_alarm") or {}).get("RECOMMENDATION") or {}
        warn = rec.get("warn_after_silent_weekday_sessions")
        alert = rec.get("alert_after_silent_weekday_sessions")
        false = rec.get("expected_false_alarms_per_year")
        density = (doc.get("quiet_alarm") or {}).get("book_day_density")
        window = (doc.get("quiet_alarm") or {}).get("window")
        armed = doc.get("armed_set")
    if not isinstance(warn, int) or not isinstance(alert, int) or warn > alert:
        raise SystemExit(f"{p} carries no usable quiet threshold for account {account}")
    return {
        "account": account,
        "warn_sessions": warn,
        "alert_sessions": alert,
        "expected_false_alarms_per_year": false,
        "measured_book_day_density": density,
        "measured_window": window,
        "armed_set": armed,
        "source": str(p.relative_to(REPO)) if p.is_relative_to(REPO) else str(p),
    }


def silence_state(last_fill: dt.date, today: dt.date, thresholds: dict) -> dict:
    """Pure. (last fill, today, thresholds) -> the operator message.

    `WARN` and `ALERT` are the archive's own 95th and 99th percentile inter-book-day gaps on
    the armed set's full-surface window. They are statements about the DISTRIBUTION of
    silence, never about the engine.
    """
    silent = weekday_sessions_between(last_fill, today)
    if silent >= thresholds["alert_sessions"]:
        state = ALERT
    elif silent >= thresholds["warn_sessions"]:
        state = WARN
    else:
        state = OK
    return {
        "state": state,
        "silent_weekday_sessions": silent,
        "silent_calendar_days": (today - last_fill).days,
        "last_fill": last_fill.isoformat(),
        "today": today.isoformat(),
        "warn_at": thresholds["warn_sessions"],
        "alert_at": thresholds["alert_sessions"],
        "sessions_to_warn": max(0, thresholds["warn_sessions"] - silent),
        "sessions_to_alert": max(0, thresholds["alert_sessions"] - silent),
        "threshold_source": thresholds["source"],
        "expected_false_alarms_per_year": thresholds.get("expected_false_alarms_per_year"),
        "IS_NOT_A_LIVENESS_CHECK": (
            "a dead worker and a quiet market are indistinguishable here. Process liveness "
            "is the supervisor heartbeat's question, not this one's."),
    }


def last_fill_from_days(book_days: Iterable[dt.date]) -> dt.date | None:
    days = sorted(book_days)
    return days[-1] if days else None


def render(state: dict, th: dict) -> str:
    bar = {OK: "ok", WARN: "WARN", ALERT: "ALERT"}[state["state"]]
    lines = [
        f"book silence [{th.get('account')}]: {bar}",
        f"  last fill            {state['last_fill']}  "
        f"({state['silent_calendar_days']} calendar days ago)",
        f"  silent sessions      {state['silent_weekday_sessions']} weekday sessions "
        f"(weekends do not count)",
        f"  warn / alert at      {state['warn_at']} / {state['alert_at']} sessions",
        f"  measured on          {th.get('measured_window')} at book-day density "
        f"{th.get('measured_book_day_density')}",
        f"  armed set            {', '.join(th.get('armed_set') or [])}",
        f"  thresholds from      {state['threshold_source']}",
    ]
    if state["state"] == OK:
        lines.append(f"  -> normal. {state['sessions_to_warn']} more silent sessions "
                     f"would reach WARN.")
    elif state["state"] == WARN:
        lines.append("  -> longer than 95 % of the archive's gaps. Expected about "
                     f"{(th.get('expected_false_alarms_per_year') or {}).get('warn')} times "
                     "a year with nothing wrong. Check the worker command line carries "
                     "--tags and that the terminals are connected.")
    else:
        lines.append("  -> longer than 99 % of the archive's gaps; the archive never showed "
                     "a gap this long on this book. Check process liveness FIRST (this tool "
                     "cannot see it), then the tag string and the include flags.")
    lines.append("  this message stops nothing, sizes nothing and touches no gate.")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--account", required=True, choices=("FTMO", "redacted_account"),
                    help="account whose current armed-set threshold to load")
    ap.add_argument("--last-fill", required=True, metavar="YYYY-MM-DD",
                    help="the date of the book's most recent fill")
    ap.add_argument("--today", metavar="YYYY-MM-DD", default=None,
                    help="evaluate as of this date (default: today, UTC)")
    ap.add_argument("--receipt", default=None, help="override the threshold receipt path")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ns = ap.parse_args(argv)

    th = load_thresholds(ns.account, Path(ns.receipt) if ns.receipt else None)
    today = (dt.date.fromisoformat(ns.today) if ns.today
             else dt.datetime.now(dt.timezone.utc).date())
    st = silence_state(dt.date.fromisoformat(ns.last_fill), today, th)
    print(json.dumps({**st, "thresholds": th}, indent=1) if ns.json else render(st, th))
    # Exit code carries the state so a scheduler can branch on it without parsing.
    # 0 OK, 1 WARN, 2 ALERT. Never non-zero for an internal error — those raise.
    return {OK: 0, WARN: 1, ALERT: 2}[st["state"]]


if __name__ == "__main__":
    raise SystemExit(main())
