#!/usr/bin/env python3
"""Reconcile ``src.costs.cost_r`` against realized broker truth, trade by trade.

This is the layer's correctness proof, and it is deliberately the *hard* direction:
`cost_r` never sees a trade's realized commission. It is given only the symbol, the
account and the trade's stop distance, and must reproduce the commission the broker
actually charged.

Inputs are the 300 rows of `docs/audits/fable5-vision-audit-20260725/phase1/w7_forensics/
LIVE_TRADE_ROWS.jsonl` -- generated by `scripts/w7_live_forensics.py`, whose own residual
against both account balances is 0.00.

It also prints the null control §3.1 of the wave-3 working agreement requires: the same
comparison against the model the system actually shipped, which charges **zero**
commission (`broker_net_cost_engine.py:577-583`). A cost model that reproduces broker
truth is only interesting relative to what it replaces.
"""

from __future__ import annotations

import argparse
import collections
import json
import statistics
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from src.costs import CostTruthError, cost_r, load_broker_true_costs  # noqa: E402

ROWS = REPO / "docs/audits/fable5-vision-audit-20260725/phase1/w7_forensics/LIVE_TRADE_ROWS.jsonl"
ACCOUNT_KEY = {"ftmo": "FTMO", "redacted_account": "redacted_account"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=Path, default=ROWS)
    ap.add_argument("--era", default="w7_book", help="stack_era filter; 'all' for every row")
    ap.add_argument("-o", "--out", type=Path, default=None)
    args = ap.parse_args()

    truth = load_broker_true_costs()
    rows = [json.loads(x) for x in args.rows.read_text("utf-8-sig").splitlines() if x.strip()]
    if args.era != "all":
        rows = [r for r in rows if r.get("stack_era") == args.era]

    per_symbol: dict = collections.defaultdict(list)
    errors: list[dict] = []
    used = 0
    skipped: collections.Counter = collections.Counter()

    for r in rows:
        acct = ACCOUNT_KEY.get(r.get("account") or "")
        sym = r.get("broker_symbol")
        risk = r.get("risk_at_entry_usd")
        realized_comm = r.get("commission")
        sl_raw = r.get("risk_distance_price")
        if not (acct and sym and risk and sl_raw is not None and realized_comm is not None):
            skipped["missing_fields"] += 1
            continue
        sl = float(sl_raw)
        if sl <= 0:
            skipped["nonpositive_stop"] += 1
            continue
        try:
            br = cost_r(
                sym,
                acct,
                holding_hours=float(r.get("holding_seconds") or 0) / 3600.0,
                sl_distance_price=sl,
                entry_price=r.get("entry_price"),
                side="SHORT" if str(r.get("side", "")).lower() == "short" else "LONG",
                costs=truth,
            )
        except CostTruthError as exc:
            skipped[f"cost_truth:{exc.__class__.__name__}"] += 1
            errors.append({"symbol": sym, "account": acct, "error": str(exc)})
            continue
        used += 1
        actual_r = -float(realized_comm) / float(risk)  # positive = cost
        per_symbol[(acct, sym)].append(
            {
                "modelled_r": br.commission_r.value,
                "actual_r": actual_r,
                "coverage": br.commission_r.coverage.value,
                "abs_err": abs(br.commission_r.value - actual_r),
                "sl": sl,
            }
        )

    print(f"rows={len(rows)} used={used} skipped={dict(skipped)}\n")
    print(f"{'account':<11} {'symbol':<12} {'n':>3} {'model R':>9} {'actual R':>9} "
          f"{'mean|err|':>10} {'max|err|':>9}  coverage")
    all_err: list[float] = []
    all_actual: list[float] = []
    for (acct, sym), recs in sorted(per_symbol.items()):
        m = statistics.fmean(x["modelled_r"] for x in recs)
        a = statistics.fmean(x["actual_r"] for x in recs)
        e = statistics.fmean(x["abs_err"] for x in recs)
        mx = max(x["abs_err"] for x in recs)
        all_err.extend(x["abs_err"] for x in recs)
        all_actual.extend(x["actual_r"] for x in recs)
        print(f"{acct:<11} {sym:<12} {len(recs):>3} {m:>9.4f} {a:>9.4f} {e:>10.6f} "
              f"{mx:>9.6f}  {recs[0]['coverage']}")

    pooled_actual = statistics.fmean(all_actual) if all_actual else 0.0
    pooled_err = statistics.fmean(all_err) if all_err else 0.0
    worst = max(all_err) if all_err else 0.0
    print(f"\npooled actual commission   : {pooled_actual:.6f} R over {len(all_actual)} fills")
    print(f"cost_r mean absolute error : {pooled_err:.6f} R  (worst single fill {worst:.6f} R)")
    # The null control: the model the system shipped.
    null_err = statistics.fmean(abs(0.0 - a) for a in all_actual) if all_actual else 0.0
    print(f"NULL CONTROL -- shipped model charges 0.0 commission "
          f"(broker_net_cost_engine.py:577-583)")
    print(f"   its mean absolute error : {null_err:.6f} R")
    if pooled_err > 0:
        print(f"   cost_r is {null_err / pooled_err:.0f}x more accurate than the shipped model")

    if errors:
        print(f"\n{len(errors)} rows could not be priced:")
        for e in errors[:10]:
            print("   ", e["account"], e["symbol"], e["error"][:120])

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(
            json.dumps(
                {
                    "schema": "gtos.broker_truth.cost_layer_reconciliation.v1",
                    "rows_considered": len(rows),
                    "rows_priced": used,
                    "skipped": dict(skipped),
                    "pooled_actual_commission_r": pooled_actual,
                    "cost_r_mean_abs_error_r": pooled_err,
                    "cost_r_worst_abs_error_r": worst,
                    "null_control_zero_commission_mean_abs_error_r": null_err,
                    "by_symbol": {
                        f"{a}:{s}": {
                            "n": len(v),
                            "modelled_r": statistics.fmean(x["modelled_r"] for x in v),
                            "actual_r": statistics.fmean(x["actual_r"] for x in v),
                            "mean_abs_error_r": statistics.fmean(x["abs_err"] for x in v),
                            "max_abs_error_r": max(x["abs_err"] for x in v),
                            "coverage": v[0]["coverage"],
                        }
                        for (a, s), v in sorted(per_symbol.items())
                    },
                    "unpriceable": errors,
                },
                indent=1,
                sort_keys=True,
            )
        )
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
