"""Render MC_FIRM_TRUE_V1.json as markdown. Every table in MC_FIRM_TRUE_V1.md comes from
here, so no number in it is transcribed by hand.

    python3 scripts/report_mc_firm_true.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ROUTE = REPO / "research/operations/w7_recost_2026_07_27"
SRC = ROUTE / "MC_FIRM_TRUE_V1.json"
PUB = ROUTE / "SURVIVOR_BOOK_V1.json"
OUT = ROUTE / "MC_FIRM_TRUE_V1.md"

# The ten rows the OD-3 dossier puts in front of Borhen (§2), in its own order.
DOSSIER_ROWS = [
    ("FTMO", "SURVIVORS_ONLY", "fwd_nights_max"),
    ("FTMO", "SURVIVORS_ONLY", "fwd_nights_1.0"),
    ("FTMO", "SURVIVORS_ONLY", "full_nights_max"),
    ("FTMO", "SURVIVORS_ONLY", "full_nights_1.0"),
    ("FTMO", "ALL_11_BOOK_OF_RECORD", "full_nights_1.0"),
    ("FTMO", "ALL_11_BOOK_OF_RECORD", "full_nights_max"),
    ("redacted_account", "SURVIVORS_ONLY", "fwd_nights_max"),
    ("redacted_account", "SURVIVORS_ONLY", "full_nights_max"),
    ("redacted_account", "ALL_11_BOOK_OF_RECORD", "full_nights_max"),
    ("redacted_account", "ALL_11_BOOK_OF_RECORD", "fwd_nights_max"),
]
CARRY = {"nights_0.0": "0 nights", "nights_1.0": "1 night", "nights_max": "WORST"}
BOOK = {"ALL_11_BOOK_OF_RECORD": "ALL 11", "SURVIVORS_ONLY": "SURVIVORS",
        "SURVIVORS_BOTH_ACCOUNTS": "BOTH-3"}
VARIANTS = ("ALL_11_BOOK_OF_RECORD", "SURVIVORS_ONLY", "SURVIVORS_BOTH_ACCOUNTS")
KEYS = ("full_nights_0.0", "full_nights_1.0", "full_nights_max",
        "fwd_nights_0.0", "fwd_nights_1.0", "fwd_nights_max")
WINDOW = {"full": "2015-26", "fwd": "fwd 2025+"}


def label(key):
    w, _, n = key.partition("_")
    return f"{WINDOW[w]} / {CARRY[n]}"


def cell(d, acct, var, key):
    return d["accounts"][acct]["variants"][var][key]


def pub_cell(p, acct, var, key):
    return p["accounts"][acct]["variants"][var][key]


def fmt(x, n=5):
    return "—" if x is None else f"{x:.{n}f}" if isinstance(x, float) else str(x)


def main():
    d = json.loads(SRC.read_text())
    p = json.loads(PUB.read_text())
    L = []
    w = L.append

    w("# MC_FIRM_TRUE_V1 — the survivor-book Monte Carlo at each firm's measured rules")
    w("")
    w(f"Generated by `scripts/report_mc_firm_true.py` from `{SRC.name}`. "
      f"**{d['n_paths']:,} paths per cell** against the sealed engine's 20,000.")
    w("")
    w("Controls (all must be zero): series-reconstruction mismatches "
      f"**{d['controls']['series_reconstruction_mismatches']}**, bit-identity disagreements "
      f"vs `INTEG_portfolio_build_w2.mc_series` **{d['controls']['bit_identity_disagreements']}** "
      f"over {d['controls']['bit_identity_cells']} cells "
      f"x {d['controls']['bit_identity_paths']:,} paths.")
    w("")

    # ---- 1. the ten dossier rows -------------------------------------------------
    w("## 1. The ten figures the OD-3 dossier puts in front of the owner")
    w("")
    w("`published` is `SURVIVOR_BOOK_V1.json` at 20,000 paths — the number in the dossier.")
    w("`L0` is this engine re-running the *same* rules at "
      f"{d['n_paths']:,} paths, so `L0 - published` is pure Monte-Carlo noise and")
    w("`firm-true - L0` is the whole effect of the rule correction.")
    w("")
    w("| account | book / window / carry | published (8%) | L0 same rules | "
      "**firm-true ph1** | Δ vs L0 | firm-true 2-step |")
    w("|---|---|---:|---:|---:|---:|---:|")
    for acct, var, key in DOSSIER_ROWS:
        c = cell(d, acct, var, key)
        pc = pub_cell(p, acct, var, key)
        l0 = c["rules"]["L0_LEGACY_SEALED"]["p_pass"]
        ft = c["rules"]["L4_FIRM_TRUE_PH1"]["p_pass"]
        two = c["rules"]["P2_BOTH_PHASES"]["p_pass"]
        book = BOOK[var]
        w(f"| {acct} | {book} / {label(key)} | {pc['p_pass']:.5f} | {l0:.5f} | "
          f"**{ft:.5f}** | {ft - l0:+.5f} | {two:.5f} |")
    w("")

    # ---- 2. decomposition ---------------------------------------------------------
    w("## 2. Which of the three rule errors did the moving")
    w("")
    w("One axis at a time, from the sealed rule set. `L4` applies all three together.")
    w("")
    w("| account | book / window / carry | L0 sealed | L1 target only | L2 daily only | "
      "L3 maxDD only | **L4 all three** |")
    w("|---|---|---:|---:|---:|---:|---:|")
    for acct, var, key in DOSSIER_ROWS:
        c = cell(d, acct, var, key)["rules"]
        book = BOOK[var]
        w(f"| {acct} | {book} / {label(key)} | {c['L0_LEGACY_SEALED']['p_pass']:.5f} | "
          f"{c['L1_TARGET_ONLY']['p_pass']:.5f} | {c['L2_DAILY_ONLY']['p_pass']:.5f} | "
          f"{c['L3_MAXDD_ONLY']['p_pass']:.5f} | **{c['L4_FIRM_TRUE_PH1']['p_pass']:.5f}** |")
    w("")
    w("Deltas from L0, so the sign of each axis is readable directly:")
    w("")
    w("| account | book / window / carry | target 8→firm | daily %→cash | maxDD trail→static "
      "| net |")
    w("|---|---|---:|---:|---:|---:|")
    for acct, var, key in DOSSIER_ROWS:
        c = cell(d, acct, var, key)["rules"]
        b = c["L0_LEGACY_SEALED"]["p_pass"]
        book = BOOK[var]
        w(f"| {acct} | {book} / {label(key)} | {c['L1_TARGET_ONLY']['p_pass'] - b:+.5f} | "
          f"{c['L2_DAILY_ONLY']['p_pass'] - b:+.5f} | "
          f"{c['L3_MAXDD_ONLY']['p_pass'] - b:+.5f} | "
          f"**{c['L4_FIRM_TRUE_PH1']['p_pass'] - b:+.5f}** |")
    w("")

    # ---- 3. full grid -------------------------------------------------------------
    w(f"## 3. The full grid, both accounts, all "
      f"{sum(len(v) for a in d['accounts'].values() for v in a['variants'].values())} cells")
    w("")
    for acct in ("FTMO", "redacted_account"):
        fr = d["accounts"][acct]["firm_rules"]
        w(f"### {acct} — phase 1 {fr['target_ph1']*100:.0f} %, phase 2 "
          f"{fr['target_ph2']*100:.0f} %, daily {fr['daily_limit']*100:.0f} % of initial "
          f"(cash), overall {fr['maxdd_limit']*100:.0f} % static, min "
          f"{fr['minimum_trading_days']} trading days")
        w("")
        w(f"survivor set: `{'`, `'.join(d['survivor_sets'][acct])}`")
        w("")
        w("| book | window / carry | eff risk % | mean R/bookday | p_pass ph1 | p_fail_dd | "
          "p_fail_daily | p_timeout | med book-d | med cal-d | %/mo cal | p_pass 2-step |")
        w("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for var in VARIANTS:
            for key in KEYS:
                c = cell(d, acct, var, key)
                r = c["rules"]["L4_FIRM_TRUE_PH1"]
                t = c["rules"]["P2_BOTH_PHASES"]
                book = BOOK[var]
                w(f"| {book} | {label(key)} | {c['eff_risk_pct']:.3f} | "
                  f"{c['mean_r_per_book_day']:.5f} | **{r['p_pass']:.5f}** | "
                  f"{r['p_fail_dd']:.5f} | {r['p_fail_daily']:.5f} | {r['p_timeout']:.5f} | "
                  f"{fmt(r['median_book_days_to_pass'])} | "
                  f"{fmt(r['median_calendar_days_to_pass'])} | "
                  f"{r['monthly_pct_calendar']:.3f} | {t['p_pass']:.5f} |")
        w("")

    # ---- 4. phases ----------------------------------------------------------------
    w("## 4. Phase 2 — a book that clears phase 1 and stalls in phase 2 has passed nothing")
    w("")
    w("`P1` is phase 2 run alone from a fresh account (5 % target). `P2` is the real "
      "2-step: phase 1, reset to the initial balance, then phase 2, on one continuous "
      "bootstrap path. `P4` is the same with the sealed trailing-drawdown rule instead of "
      "the measured static floor.")
    w("")
    w("| account | book / window / carry | ph1 | ph2 alone | **2-step** | ph1 x ph2 | "
      "2-step, trailing DD | med cal-d 2-step |")
    w("|---|---|---:|---:|---:|---:|---:|---:|")
    for acct, var, key in DOSSIER_ROWS:
        c = cell(d, acct, var, key)["rules"]
        one = c["L4_FIRM_TRUE_PH1"]["p_pass"]
        alone = c["P1_PHASE2_ALONE"]["p_pass"]
        two = c["P2_BOTH_PHASES"]
        book = BOOK[var]
        w(f"| {acct} | {book} / {label(key)} | {one:.5f} | {alone:.5f} | "
          f"**{two['p_pass']:.5f}** | {one*alone:.5f} | "
          f"{c['P4_BOTH_PHASES_TRAILING_DD']['p_pass']:.5f} | "
          f"{fmt(two['median_calendar_days_to_pass'])} |")
    w("")

    # ---- 5. minimum trading days ---------------------------------------------------
    w("## 5. Minimum trading days — configured for neither account in the MC, and inert")
    w("")
    w("FTMO requires 4 trading days per phase, redacted_account 5 [both MEASURED]. The sealed "
      "engine models neither. `latch` = stop risking on reaching target and wait out the "
      "minimum; `at_risk` = keep trading the book at full size, which is a bound, not an "
      "expectation.")
    w("")
    w("| account | book / window / carry | ph1 | +min days (latch) | +min days (at risk) |")
    w("|---|---|---:|---:|---:|")
    for acct, var, key in DOSSIER_ROWS:
        c = cell(d, acct, var, key)["rules"]
        w(f"| {acct} | {BOOK[var]} / "
          f"{label(key)} | {c['L4_FIRM_TRUE_PH1']['p_pass']:.5f} | "
          f"{c['L6_FIRM_TRUE_PH1_MINDAYS_LATCH']['p_pass']:.5f} | "
          f"{c['L7_FIRM_TRUE_PH1_MINDAYS_ATRISK']['p_pass']:.5f} |")
    w("")

    # ---- 6. daily headroom ---------------------------------------------------------
    w("## 6. The daily-loss denominator — deterministic, not simulated")
    w("")
    w("The bootstrap only ever draws days that exist in the series, so the largest "
      "single-day loss any path can take is `min(series) x risk`, on a day-start equity of "
      "at most `1 + target`. Where that is smaller than the 5 % allowance, **no path can "
      "breach under either denominator** and the choice is provably irrelevant — a stronger "
      "statement than `p_fail_daily = 0`.")
    w("")
    w("| account | book | window / carry | worst day, % of equity | legacy can fire | "
      "firm can fire | % of the 5 % allowance used |")
    w("|---|---|---|---:|---|---|---:|")
    for h in d["daily_rule_headroom"]:
        w(f"| {h['account']} | "
          f"{BOOK[h['variant']]} | "
          f"{label(h['key'])} | {h['worst_day_pct_of_equity']:.3f} | "
          f"{'YES' if h['legacy_can_fire'] else 'no'} | "
          f"{'YES' if h['firm_can_fire_at_eq_1p10'] else 'no'} | "
          f"{100*h['headroom_ratio_firm']:.1f} % |")
    w("")

    # ---- 7. dial sweep -------------------------------------------------------------
    w("## 7. Risk dial, at the corrected rules")
    w("")
    w("The dossier's option A is \"canary at a reduced dial\" and nothing in the record "
      "priced it. `eff risk` is the dial after the book's own volatility match "
      "(`vol_scale`), which is what the MC actually risks per correlated unit.")
    w("")
    sweeps = ([r for r in DOSSIER_ROWS if r[1] == "SURVIVORS_ONLY"]
              + [(a, "SURVIVORS_BOTH_ACCOUNTS", k)
                 for a in ("FTMO", "redacted_account") for k in ("fwd_nights_max",)])
    for acct, var, key in sweeps:
        c = cell(d, acct, var, key)
        w(f"**{acct} — {BOOK[var]} / {label(key)}** (vol_scale {c['vol_scale']})")
        w("")
        w("| dial | eff risk % | p_pass ph1 | p_pass 2-step | med cal-days ph1 | %/mo cal |")
        w("|---|---:|---:|---:|---:|---:|")
        sw1 = c["dial_sweep"]["L4_FIRM_TRUE_PH1"]
        sw2 = c["dial_sweep"]["P2_BOTH_PHASES"]
        for dl in sorted(sw1, key=lambda s: float(s.rstrip("%"))):
            a1, a2 = sw1[dl], sw2[dl]
            w(f"| {dl} | {a1['eff_risk_pct']:.4f} | {a1['p_pass']:.5f} | "
              f"{a2['p_pass']:.5f} | {fmt(a1['median_calendar_days_to_pass'])} | "
              f"{a1['monthly_pct_calendar']:.3f} |")
        w("")

    # ---- 7b. the intersection book ---------------------------------------------------
    w("## 7b. `BOTH-3` — the book that survives on both accounts")
    w("")
    w("`SURVIVORS_ONLY` is per account and the two sets are not equal: FTMO keeps "
      "`metals_core` and drops `vp_euidx_pocgrav`, redacted_account does the reverse. "
      "`BOTH-3` is the intersection — `crypto`, `energy_agri`, `sub_xvol_pullback` — "
      "which is the book `OD3_DOSSIER_SURVIVOR_BOOK.md` §0 describes and which no "
      "published grid measures.")
    w("")
    w("| account | window / carry | book | book-days | eff risk % | mean R/bookday | "
      "p_pass ph1 | p_pass 2-step | med cal-d ph1 | %/mo cal |")
    w("|---|---|---|---:|---:|---:|---:|---:|---:|---:|")
    for acct in ("FTMO", "redacted_account"):
        for key in KEYS:
            for var in ("SURVIVORS_ONLY", "SURVIVORS_BOTH_ACCOUNTS"):
                c = cell(d, acct, var, key)
                r = c["rules"]["L4_FIRM_TRUE_PH1"]
                w(f"| {acct} | {label(key)} | {BOOK[var]} | {c['book_days']} | "
                  f"{c['eff_risk_pct']:.3f} | {c['mean_r_per_book_day']:.5f} | "
                  f"{r['p_pass']:.5f} | "
                  f"{c['rules']['P2_BOTH_PHASES']['p_pass']:.5f} | "
                  f"{fmt(r['median_calendar_days_to_pass'])} | "
                  f"{r['monthly_pct_calendar']:.3f} |")
    w("")

    # ---- 7c. concentration -----------------------------------------------------------
    w("## 7c. Concentration — the dominant doubt is a property of the book, so it moves")
    w("")
    w("`OD3_DOSSIER_SURVIVOR_BOOK.md` §5.1 is the doubt it says should worry the owner "
      "most: *\"46.9 % of the edge sits on 194 trades\"* in `crypto` and "
      "`sub_xvol_pullback`, neither with an out-of-sample window. Kelly columns, signed "
      "denominator — B161's own stated basis.")
    w("")
    w("| account | window / carry | book | crypto | sub_xvol_pullback | **the two together** "
      "| rest |")
    w("|---|---|---|---:|---:|---:|---|")
    cs = d["contribution_shares"]
    for acct in ("FTMO", "redacted_account"):
        for key in KEYS:
            for var in VARIANTS:
                e = cs[f"{acct}|{var}|{key}"]
                if e["degenerate"]:
                    w(f"| {acct} | {label(key)} | {BOOK[var]} | — | — | — | "
                      f"*winners and losers cancel (net {e['signed_total']:+.2f} of "
                      f"{e['abs_total']:.2f} gross); no share is meaningful* |")
                    continue
                v = e["shares"]
                a, b = v.get("crypto", 0.0), v.get("sub_xvol_pullback", 0.0)
                rest = ", ".join(f"{s} {x:.1f}" for s, x in v.items()
                                 if s not in ("crypto", "sub_xvol_pullback"))
                w(f"| {acct} | {label(key)} | {BOOK[var]} | {a:.1f} | {b:.1f} | "
                  f"**{a + b:.1f}** | {rest} |")
    w("")

    # ---- 8. nulls ------------------------------------------------------------------
    w("## 8. Null controls")
    w("")
    w("`zero drift` re-runs the identical cell with the series demeaned — same volatility, "
      "same fat tail, same block structure, **no edge**. It answers how much of `p_pass` is "
      "the book and how much is the geometry of a +target/−10 % barrier problem. "
      "`seed spread` is the range of `p_pass` over three seed bases at the sealed rules — "
      "the Monte-Carlo noise floor a rule effect has to beat.")
    w("")
    w("| account | book | window / carry | p_pass firm-true | zero-drift, firm rules | "
      "zero-drift, legacy | seed spread |")
    w("|---|---|---|---:|---:|---:|---:|")
    for acct in ("FTMO", "redacted_account"):
        for var in VARIANTS:
            for key in KEYS:
                c = cell(d, acct, var, key)
                n = c["null_controls"]
                w(f"| {acct} | {BOOK[var]} | "
                  f"{label(key)} | {c['rules']['L4_FIRM_TRUE_PH1']['p_pass']:.5f} | "
                  f"{n['zero_drift_firm_true']:.5f} | {n['zero_drift_legacy']:.5f} | "
                  f"{n['seed_noise_spread']:.5f} |")
    w("")
    w("---")
    w("")
    w(f"`{SRC.name}` is the artifact; this file is a rendering of it. "
      "`scripts/mc_firm_rules.py` regenerates both.")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
