"""Render ARMED_SET_MC_V1.json as markdown. Every table in ARMED_SET_MC_V1.md comes from
here, so no number in it is transcribed by hand.

    python3 scripts/report_armed_set_mc.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ROUTE = REPO / "research/operations/w7_recost_2026_07_27"
SRC = ROUTE / "ARMED_SET_MC_V1.json"
PUB = ROUTE / "SURVIVOR_BOOK_V1.json"
OUT = ROUTE / "ARMED_SET_MC_V1.md"

SETS = ("ARMED_4", "CONF_FLOOR_3", "BOTH_3", "ALL_11_BOOK_OF_RECORD")
SHORT = {"ARMED_4": "ARMED-4", "CONF_FLOOR_3": "FLOOR-3", "BOTH_3": "BOTH-3",
         "ALL_11_BOOK_OF_RECORD": "ALL-11"}
CARRY = {"nights_0.0": "0 nights", "nights_1.0": "1 night", "nights_max": "WORST"}
WINDOW = {"full": "2015-26", "fwd": "fwd 2025+"}
KEYS = ("fwd_nights_0.0", "fwd_nights_1.0", "fwd_nights_max",
        "full_nights_0.0", "full_nights_1.0", "full_nights_max")


def label(key):
    w, _, n = key.partition("_")
    return f"{WINDOW[w]} / {CARRY[n]}"


def f(x, n=5):
    if x is None:
        return "—"
    return f"{x:.{n}f}" if isinstance(x, float) else str(x)


def main():
    d = json.loads(SRC.read_text())
    pub = json.loads(PUB.read_text())
    L = []
    w = L.append

    w("# ARMED_SET_MC_V1 — the Monte Carlo for the book that is going to be armed")
    w("")
    w(f"Generated by `scripts/report_armed_set_mc.py` from `{SRC.name}`. "
      f"**{d['n_paths']:,} paths per cell.** Account: **{d['account']}**.")
    w("")
    c = d["controls"]
    w(f"Controls, all required to be zero: raw-matrix reconstruction **"
      f"{c['matrix_reconstruction_mismatches']}**, `mc_governed` reduces to "
      f"`mc_firm_rules.mc` **{c['governed_reduces_to_mc_disagreements']}**, "
      f"`mc_firm_rules.mc` equals `INTEG_portfolio_build_w2.mc_series` **"
      f"{c['mc_equals_sealed_engine_disagreements']}**, over {c['cells']} cells.")
    w("")

    # ---------------------------------------------------------------- 1. sizing
    w("## 1. The sizing gap")
    w("")
    w("`published` is the convention every figure the owner has seen was computed at: "
      "`risk = dial x (sd_reference / sd_variant)` (`build_survivor_book.py:64`). `live` is "
      "what the deployable path does: `base_risk = ALLOCATION_PROFILES[profile]"
      ".risk_per_unit_A` (`admission.py:1470`), then `x gov.size_cap_multiplier` (`:1521`, "
      "<= 1.0) and `unit_risk = base x conf x derisk_mult` (`:1212`) — **no volatility term "
      "in the configured profile.** Stated that way on purpose: the module does carry a vol "
      "term, `CLEAN3_VOL_SCALE = 0.9481` pre-multiplied into every W5 `clean3_*` profile "
      "(`:686-731`); the W7 dials dropped it deliberately (`:752-760`). Plus the half-Kelly "
      "bins that `ultimate_book_kelly_conservative: true` selects.")
    w("")
    w("The naive multiple is `1 / vol_scale`. It is **wrong**, because half-Kelly is itself "
      "a volatility reshape and absorbs part of the gap. The measured multiple is "
      "`(sd_half / sd_full) / vol_scale`.")
    w("")
    w("| book / carry | vol_scale | published eff risk | half-Kelly reshape | live in full-Kelly units | **live / published** | naive | **dial that reproduces the published sizing** |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|")
    for name in SETS:
        for nights in ("0.0", "1.0", "max"):
            k = f"{name}|fwd_nights_{nights}"
            if k not in d["sizing_provenance"]:
                continue
            s = d["sizing_provenance"][k]
            # The dial at which the live convention delivers exactly the risk every
            # published figure assumes: dial * reshape == DIAL * vol_scale.
            equiv = 100 * (d["dial_nominal_pct"] / 100.0) * (
                s["vol_scale_published"] / s["half_kelly_reshape"])
            w(f"| {SHORT[name]} / {CARRY['nights_' + nights]} | {s['vol_scale_published']} | "
              f"{s['published_eff_risk_pct']:.3f} % | {s['half_kelly_reshape']} | "
              f"{s['live_risk_in_full_kelly_units_pct']:.3f} % | "
              f"**{s['live_multiple_over_published']}x** | "
              f"{s['naive_multiple_ignoring_kelly']}x | **{equiv:.3f} % nominal** |")
    w("")
    w("The last column is the one an operator can act on: it is the `ultimate_book_profile` "
      "nominal at which the live sizing chain delivers exactly the risk every published "
      "figure assumes. Nothing in `ALLOCATION_PROFILES` sits there — the nearest dials "
      "below the current one are `clean3_w7_measured_nom1p25` (1.25 %) and "
      "`clean3_balanced_eff0p71` (0.711 % effective, a W5 profile that pre-multiplies its "
      "own vol scale and is therefore a different convention again).")
    w("")

    cc = d["w7_certification_check"]
    if cc.get("matched_row"):
        r = cc["matched_row"]
        w("### 1a. The live dial's own certification")
        w("")
        w(f"`ALLOCATION_PROFILES[\"clean3_w7_ceiling_nom2p00\"]` carries "
          f"`base_p_both {cc['profile_stats']['base_p_both']}` / "
          f"`fwd_p_both {cc['profile_stats']['fwd_p_both']}` / "
          f"`stress15_p_both {cc['profile_stats']['stress15_p_both']}`. Searching "
          f"`INTEG_W7_FINAL_RESULT.json` for those three values returns "
          f"**{cc['matching_artifact_rows']}** — and nothing else.")
        w("")
        w("| | account A | account B |")
        w("|---|---:|---:|")
        w(f"| the certifying row's nominal | {r['sizeA_nominal']} | {r['sizeB_nominal']} |")
        w(f"| the certifying row's **effective** | {r['sizeA_eff']} | {r['sizeB_eff']} |")
        w(f"| the live profile | {cc['profile_risk_per_unit_A']} | "
          f"{cc['profile_risk_per_unit_B']} |")
        w("")
        w(f"The locked MC vol-matched at `VS_final = {cc['locked_vs_final']}`. The live "
          f"package justifies dropping that by asserting the Kelly-lite multiplier IS the "
          f"reshape. **Measured on the same basis it is "
          f"{cc['half_kelly_reshape_on_locked_basis']}**, so the claim "
          f"{'holds' if cc['reshape_claim_holds'] else 'does not hold'}: live runs "
          f"{cc['live_eff_in_full_kelly_units_pct']:.3f} % against a certified "
          f"{cc['locked_eff_risk_A_pct']:.3f} %, i.e. **{cc['live_over_certified']}x** its "
          f"own certification — and the certifying row ran account B at 1.50 % nominal "
          f"while the profile sets both accounts to 2.00 %.")
        w("")

    # ---------------------------------------------------------------- 2. grid
    w("## 2. Every set, every carry, both sizing conventions")
    w("")
    w("`L4` is FTMO's measured phase-1 rules (10 % target, static $90,000 floor, cash daily "
      "limit); `P2` is the whole 2-step evaluation. Both are Q's rule sets, unchanged.")
    w("")
    for key in KEYS:
        w(f"### {label(key)}")
        w("")
        w("| book | days | eff risk | mean R/day | worst day | **L4 p_pass** | cal-d | %/mo | **P2 p_pass** | P2 cal-d |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for name in SETS:
            g = d["grid"][name][key]
            for conv in ("published", "live"):
                s = g[conv]
                l4, p2 = s["rules"]["L4_FIRM_TRUE_PH1"], s["rules"]["P2_BOTH_PHASES"]
                tag = SHORT[name] + ("" if conv == "published" else " *live*")
                w(f"| {tag} | {g['book_days']} | {s['eff_risk_pct']:.3f} % | "
                  f"{s['mean_r_per_book_day']:.4f} | {s['worst_day_pct_of_equity']:.2f} % | "
                  f"**{f(l4['p_pass'])}** | {l4['median_calendar_days_to_pass']} | "
                  f"{l4['monthly_pct_calendar']} | **{f(p2['p_pass'])}** | "
                  f"{p2['median_calendar_days_to_pass']} |")
        w("")

    # ---------------------------------------------------------------- 3. governor
    w("## 3. The live governor")
    w("")
    w("`live_uncapped` is the live sizing with no governor. `gross_cap_4pct` adds the 4 % "
      "gross open-risk ceiling, first-fit-descending, exactly as "
      "`admission._enforce_gross_open_risk_cap` sheds. `+smooth_derisk` adds "
      "`derisk_mode: smooth` measured from the **static** initial balance, plus the -9 % "
      "entry block — which is absorbing in this model and is counted as a failure, not a "
      "timeout.")
    w("")
    w("| book / carry | model | L4 p_pass | cal-d | P2 p_pass | P2 cal-d | cap binds |")
    w("|---|---|---:|---:|---:|---:|---:|")
    for name in ("ARMED_4", "CONF_FLOOR_3", "BOTH_3"):
        for nights in ("0.0", "1.0", "max"):
            k = f"fwd_nights_{nights}"
            row = d["live_governor"][name][k]
            for lab in ("live_uncapped", "live_gross_cap_4pct",
                        "live_gross_cap_and_smooth_derisk"):
                l4, p2 = row[lab]["L4_FIRM_TRUE_PH1"], row[lab]["P2_BOTH_PHASES"]
                share = l4.get("gross_cap_bound_day_share")
                w(f"| {SHORT[name]} / {CARRY['nights_' + nights]} | "
                  f"{lab.replace('live_', '')} | {f(l4['p_pass'])} | "
                  f"{l4['median_calendar_days_to_pass']} | {f(p2['p_pass'])} | "
                  f"{p2['median_calendar_days_to_pass']} | "
                  f"{'—' if share is None else f'{100 * share:.2f} %'} |")
    w("")

    # ---------------------------------------------------------------- 4. from here
    fh = d["from_here"]
    w("## 4. From here")
    w("")
    w(f"FTMO equity **${fh['equity_witnessed']:,.2f}** "
      f"(`{fh['source']}`). "
      f"It needs **${fh['remaining_usd']:,.2f}** more — "
      f"{fh['remaining_to_phase1_target_pct_of_initial']:.3f} % of the initial balance, "
      f"{fh['remaining_to_phase1_target_pct_of_current_equity']:.3f} % of current equity — "
      f"against **${fh['headroom_to_static_floor_usd']:,.2f}** of room to the static "
      f"$90,000 floor.")
    w("")
    w("| book / carry | sizing | model | p_pass | book-d | cal-d |")
    w("|---|---|---|---:|---:|---:|")
    for name in ("ARMED_4", "CONF_FLOOR_3", "BOTH_3"):
        for nights in ("0.0", "1.0", "max"):
            k = f"{name}|fwd_nights_{nights}"
            for conv in ("published", "live"):
                for lab, v in fh["cells"][k][conv].items():
                    w(f"| {SHORT[name]} / {CARRY['nights_' + nights]} | {conv} | {lab} | "
                      f"{f(v['p_pass'])} | {v['median_book_days_to_pass']} | "
                      f"{v['median_calendar_days_to_pass']} |")
    w("")

    fhg = d.get("from_here_governed")
    if fhg:
        w("### 4a. From here, with the whole live governor")
        w("")
        w(fhg["_note"])
        w("")
        w("| book / carry | start | rule | p_pass | cal-d | entry-block |")
        w("|---|---|---|---:|---:|---:|")
        for k, v in fhg.items():
            if k == "_note":
                continue
            for lab, x in v.items():
                start, _, rlab = lab.partition("|")
                w(f"| {k.replace('|', ' / ')} | {start} | {rlab} | {f(x['p_pass'])} | "
                  f"{x['median_calendar_days_to_pass']} | {x['p_fail_entry_block']} |")
        w("")

    # ---------------------------------------------------------------- 5. concentration
    w("## 5. Concentration")
    w("")
    w(d["concentration"]["question"])
    w("")
    w(f"Haircut model: {d['concentration']['haircut_model']}")
    w("")
    w(f"Shared-sleeve rule: {d['concentration']['shared_sleeve_rule']}")
    w("")
    for nights in ("0.0", "1.0", "max"):
        k = f"fwd_nights_{nights}"
        n = d["concentration"][k]
        w(f"### {CARRY['nights_' + nights]}")
        w("")
        t = n["window_totals"]
        w(f"Window totals (live sizing, unit-R): ARMED-4 **{t['armed4_total_r']}** over "
          f"{t['armed4_book_days']} book-days, FLOOR-3 **{t['conf_floor3_total_r']}** over "
          f"{t['conf_floor3_book_days']}.")
        pb = n["paired_bootstrap"]
        w("")
        w(f"The two books differ by one sleeve, so the difference series is exactly 0.0 on "
          f"every day it did not fire: **{pb['union_days']} union days, "
          f"{pb['effective_nonzero_days']} of them non-zero**. Observed advantage "
          f"**{pb['observed_diff_total_r']} R**. "
          f"**Exact sign-flip p(advantage <= 0) = {pb['p_advantage_le_zero_exact_sign_flip']}** "
          f"over all 2^{pb['effective_nonzero_days']} patterns — that is the number to use. "
          f"The circular block bootstrap gives "
          f"{pb['p_advantage_le_zero_block_bootstrap']} at block {pb['block']} "
          f"(95 % CI {pb['ci95']}), and it is anti-conservative.")
        w("")
        ac = n["daily_autocorrelation"]
        w(f"Block-length evidence: daily-series rho_1..10 = {ac['rho_1_to_10']} against a "
          f"+/-{ac['two_over_sqrt_n']} band, variance inflation factor "
          f"**{ac['variance_inflation_factor_10_lags']}**. Session R's rho_1 0.441 for "
          f"`crypto` describes the *firing* pattern on a session axis; on the book-day axis "
          f"the firing indicator is identically 1, and the bootstrap resamples returns — so "
          f"the returns are what set the block. Block sensitivity: "
          f"{n['paired_bootstrap_block_sensitivity']}.")
        w("")
        w("**The null a zero-edge fourth sleeve sets.** Adding any sleeve raises `n_active` "
          "on the days it fires, which raises the Kelly multiplier for the other three — so "
          "\"beats FLOOR-3\" is not a coin flip at 50 %.")
        w("")
        w("| null | P(zero-edge sleeve beats FLOOR-3) | null advantage median | null p95 | **P(null >= observed)** |")
        w("|---|---:|---:|---:|---:|")
        for lab, v in n["zero_edge_null"].items():
            w(f"| {lab} | **{v['p_zero_edge_sleeve_beats_floor3']}** | "
              f"{v['null_advantage_median']} | {v['null_advantage_p95']} | "
              f"**{v['p_null_advantage_ge_observed']}** |")
        w("")
        w("| leave-one-out | book-days | total R | sd | share of ARMED-4 | L4 p_pass | cal-d | %/mo | **passes/yr** |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
        for lab, v in n["leave_one_out"].items():
            w(f"| {lab} | {v['book_days']} | {v['total_r']} | {v['sd_unit_r']} | "
              f"{v['share_of_armed4_total']} | "
              f"{f(v['p_pass'])} | {v['median_calendar_days_to_pass']} | "
              f"{v['monthly_pct_calendar']} | **{v['expected_passes_per_year']}** |")
        w("")
        w("`p_pass` inverts the ranking here and `passes/yr` does not: dropping `crypto` "
          "cuts the book's daily sd far more than its mean, so the drawdown barrier becomes "
          "nearly unreachable while the book loses a third of its trading days. Read the "
          "last column.")
        w("")
        w(f"Break-even haircut on `sub_xvol_pullback`: advantage is "
          f"**{n['advantage_at_lambda_1']} R** at lambda 1 and "
          f"**{n['advantage_at_lambda_0']} R** at lambda 0, exactly linear in between "
          f"(residual {n['breakeven_linearity_residual']}), so the break-even is "
          f"**lambda = {n['breakeven_lambda_vs_conf_floor3']}**. {n['breakeven_note']}")
        w("")
        w("| sleeve | shared | model | lambda | ARMED-4 total R | FLOOR-3 at same lambda | advantage | beats | L4 p_pass | %/mo |")
        w("|---|---|---|---:|---:|---:|---:|---|---:|---:|")
        for sl in n["haircut"]:
            for model in n["haircut"][sl]:
                for lam, v in n["haircut"][sl][model].items():
                    w(f"| {sl} | {'both' if v['shared_with_conf_floor3'] else 'ARMED-4 only'}"
                      f" | {model} | {lam.replace('lambda_', '')} | {v['total_r']} | "
                      f"{v['conf_floor3_total_r_at_same_lambda']} | "
                      f"{v['total_r_vs_conf_floor3']} | "
                      f"{'yes' if v['beats_conf_floor3'] else '**no**'} | "
                      f"{f(v['p_pass'])} | {v['monthly_pct_calendar']} |")
        w("")

    # ---------------------------------------------------------------- 6. frequency
    w("## 6. Firing frequency — the multiplier in every monthly figure")
    w("")
    w("`monthly_pct_calendar = mean_r_per_book_day x risk x book_days_per_calendar_month`, "
      "so the headline is **linear** in the last term. The published headline uses 7.11. "
      "Here is the distribution behind it.")
    w("")
    w("| book / window | months | mean | median | p10 | p90 | min | max | zero-months | share <=3 |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for k, v in d["frequency"].items():
        w(f"| {k} | {v['n_calendar_months']} | {v['mean']} | {v['median']} | {v['p10']} | "
          f"{v['p90']} | {v['min']} | {v['max']} | {v['months_with_zero_book_days']} | "
          f"{v['share_months_at_or_below_3']} |")
    w("")

    # ------------------------------------------------- 6b. the intra_size convention
    isc = d.get("intra_size_convention")
    if isc:
        w("## 6b. `intra_size` — a fourth sizing divergence")
        w("")
        w(isc["_note"])
        w("")
        w("| book / carry | mean research intra_size | total R research | total R live | "
          "worst day research | worst day live | L4 research | L4 live |")
        w("|---|---|---:|---:|---:|---:|---:|---:|")
        for k, v in isc.items():
            if k == "_note":
                continue
            r, l = v["research_convention"], v["live_convention_intra_1"]
            mi = ", ".join(f"{s} {x}" for s, x in v["mean_research_intra_size"].items())
            w(f"| {k.replace(chr(124), ' / ')} | {mi} | {r['total_r']} | {l['total_r']} | "
              f"{r['worst_day_pct']:.2f} % | **{l['worst_day_pct']:.2f} %** | "
              f"{f(r['p_pass'].get('L4_FIRM_TRUE_PH1'))} | "
              f"{f(l['p_pass'].get('L4_FIRM_TRUE_PH1'))} |")
        w("")
        w("The live convention is *better* on edge and *worse* on the tail. The worst day of "
          "the armed book's forward history moves from −3.28 % to **−4.12 %** of equity, "
          "which is past `ultimate_book_flatten_daily_loss_pct: 0.04` — the last-resort "
          "flatten tier would fire on it.")
        w("")

    # ------------------------------------------- 6c. outside the selection window
    osw = d.get("outside_the_selection_window")
    if osw:
        w("## 6c. Outside the selection window")
        w("")
        w(osw["_note"])
        w("")
        w("| book / window | book-days | months | bd/month | density | total R | "
          "%/mo published | L4 published | P2 published | %/mo live | L4 live |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for k, v in osw.items():
            if k == "_note":
                continue
            p_, l_ = v["published"], v["live"]
            w(f"| {k.replace(chr(124), ' / ')} | {v['book_days']} | {v['calendar_months']} | "
              f"{v['book_days_per_calendar_month']} | {v['density_pct']} % | "
              f"{v['total_r']} | **{p_['monthly_pct_calendar']}** | "
              f"{f(p_['rules']['L4_FIRM_TRUE_PH1']['p_pass'])} | "
              f"{f(p_['rules']['P2_BOTH_PHASES']['p_pass'])} | "
              f"{l_['monthly_pct_calendar']} | "
              f"{f(l_['rules']['L4_FIRM_TRUE_PH1']['p_pass'])} |")
        w("")

    # ---------------------------------------------------------------- 7. published
    p = pub["accounts"]["FTMO"]["variants"]["SURVIVORS_ONLY"]["fwd_nights_max"]
    w("## 7. The published headline, for reference")
    w("")
    w(f"`SURVIVOR_BOOK_V1.json` FTMO / SURVIVORS_ONLY / fwd_nights_max: "
      f"`p_pass {p['p_pass']}`, `monthly_pct_calendar {p['monthly_pct_calendar']}`, "
      f"`median_calendar_days_to_pass {p['median_calendar_days_to_pass']}`, "
      f"`book_days_per_calendar_month {p['book_days_per_calendar_month']}`, "
      f"**`eff_risk_pct {p['eff_risk_pct']}`**.")
    w("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
