"""The gate chains must agree with the LIVE ENGINE, not with a reading of it.

`X_ESTATE_TRADES.json.gz` was generated by driving `GenerationPort`, which constructs the
production `UltimateBookLiveEngine` and calls `_generate_intents` — the same method
`book_engine.py:720` calls in production. Comparing this package's fire set against that
artifact is therefore a comparison against production, which is the only comparison worth
making. `test_regime_spine_state.py` checks the arithmetic; this checks the behaviour.

THE ONE DISAGREEMENT, WHICH IS A FINDING RATHER THAN A FAILURE
----------------------------------------------------------------
This package fires on a strict SUPERSET of the port's bars, and every extra bar sits
immediately before a data gap of two intervals or more (29 of 29, measured across five
H4 sleeves). The mechanism is `bar_provider.candles_to_bars`, which drops the last
candle unconditionally: at a session close the last candle IS the freshly-closed bar, so
it is dropped, and by the time the next bar starts forming the recency guard at
`book_engine.py:512` refuses it as stale. The last closed bar before every session gap is
therefore unreachable.

So the assertion is directional — `port ⊆ ours`, plus a check that the difference is
entirely pre-gap bars — rather than set equality. Asserting equality would have required
either deleting the finding or corrupting this package to reproduce a defect.

The artifact lives in the repo, so this test does not skip.
"""

from __future__ import annotations

import datetime as dt
import gzip
import json
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
ESTATE = (REPO / "docs/audits/fable5-vision-audit-20260725/phase5/receipts"
          / "X_ESTATE_TRADES.json.gz")
CACHE = (REPO / "docs/audits/fable5-vision-audit-20260725/phase6/receipts"
         / "AB_PORT_PARITY_V1.json")

H4_SLEEVES = ("metals_core", "metals_softband", "energy_agri", "crypto",
              "sub_xvol_pullback")


def _archive_available() -> bool:
    from src.research_infra.regime_spine.archive import ARCHIVE

    return Path(ARCHIVE).is_dir()


@pytest.mark.skipif(not ESTATE.is_file(), reason="X_ESTATE_TRADES.json.gz absent")
def test_port_parity_receipt_is_committed_and_consistent():
    """The parity result is committed, so the claim survives without the bar archive.

    A test that only runs when a 130 MB out-of-repo archive is present is a test that
    silently stops running. The live comparison below still runs when the archive IS
    present; this one always runs and checks the recorded receipt is internally coherent
    and says what the module docstring says.
    """
    if not CACHE.is_file():
        pytest.skip("parity receipt not yet generated (run ab_port_parity.py)")
    d = json.loads(CACHE.read_text())
    assert d["schema"].startswith("gtos.wave6.regime_spine.port_parity")
    for sleeve, row in d["sleeves"].items():
        assert row["only_port"] == 0, (
            f"{sleeve}: the port fired {row['only_port']} bars this package does not — "
            "that is a fidelity defect, not a finding")
        assert row["geometry_mismatches"] == 0, f"{sleeve}: geometry disagreement"
        assert row["only_ours"] == row["only_ours_pre_gap"], (
            f"{sleeve}: {row['only_ours'] - row['only_ours_pre_gap']} extra fires are NOT "
            "pre-gap bars, so the documented mechanism does not explain them")


@pytest.mark.skipif(not _archive_available(), reason="VPS bar archive not on this machine")
@pytest.mark.skipif(not ESTATE.is_file(), reason="X_ESTATE_TRADES.json.gz absent")
def test_fire_set_is_a_superset_of_the_ports_and_the_difference_is_pre_gap():
    from src.research_infra.regime_spine import conditions as C
    from src.research_infra.regime_spine.archive import frames_for

    est = json.load(gzip.open(ESTATE, "rt"))
    want = sorted({s for n in H4_SLEEVES for s in C.SLEEVES[n].surface})
    frames = frames_for(want, 16388)
    ivl = dt.timedelta(hours=4)

    # The port artifact (`AQ_ESTATE_TRADES_V2`) is a DATED walk of the surface each sleeve carried
    # when it was generated. `conditions.py` derives `surface` from the LIVE sleeve module, so a
    # surface widening puts symbols in the fire set that the port could not contain -- a scope
    # mismatch, not a fidelity defect. ETHUSD joined `crypto` on 2026-08-11 (owner-authorized,
    # lane B7). Compare on the intersection: the port's own symbols.
    port_symbols = {name: {r["symbol"] for r in est["trades"].get(name, [])} for name in H4_SLEEVES}

    for name in H4_SLEEVES:
        cond = C.SLEEVES[name]
        ours, geo = set(), {}
        for canon in cond.surface:
            f = frames.get(canon)
            if f is None:
                continue
            # filter on the FRAME's symbol, which is the space the port keys live in --
            # `cond.surface` carries canonical names and the port carries broker names
            if f.symbol not in port_symbols[name]:
                continue
            for i, intent in C.fires(f, cond):
                key = (f.symbol, f.times_utc[i].isoformat())
                ours.add(key)
                nxt = (f.times_utc[i + 1] - f.times_utc[i]) if i + 1 < len(f) else None
                geo[key] = (intent, nxt)
        port = {(r["symbol"], r["decision_bar_iso"])
                for r in est["trades"].get(name, [])}
        assert port, f"{name} has no port trades to compare against"

        # Wave-21 measured that the pre-2007 US DST calendar in broker_clock was
        # wrong (EPAct rule applied before 2007; the Uniform Time Act rule
        # governs 1987-2006). The sealed port artifact was generated under the
        # OLD conversion, so a port bar inside a calendar-divergence window
        # carries a UTC label exactly one hour EARLY. Accept a missing port bar
        # ONLY when it is pre-2007 and its +1h relabel is a fired bar -- any
        # other discrepancy still fails as a fidelity defect.
        def _old_clock_relabel(key):
            sym, iso = key
            if iso >= "2007":
                return None
            fixed = (dt.datetime.fromisoformat(iso)
                     + dt.timedelta(hours=1)).isoformat()
            return (sym, fixed) if (sym, fixed) in ours else None

        relabeled = {key: _old_clock_relabel(key) for key in (port - ours)}
        unexplained = [key for key, fixed in relabeled.items() if fixed is None]
        assert not unexplained, (
            f"{name}: the port fired {len(unexplained)} bars this package does "
            f"not, beyond the known pre-2007 old-clock relabel: {unexplained}")
        for r in est["trades"][name]:
            key = (r["symbol"], r["decision_bar_iso"])
            intent, _ = geo[relabeled.get(key) or key]
            assert intent["direction"] == r["direction"]
            assert intent["stop_dist"] == pytest.approx(r["sl_distance_price"], abs=1e-12)
        relabel_targets = {fixed for fixed in relabeled.values() if fixed}
        for key in ours - port - relabel_targets:
            _intent, nxt = geo[key]
            assert nxt is not None and nxt > ivl, (
                f"{name}: {key} fires here and not in the port, and is NOT a pre-gap bar")


def test_gate_chains_declare_a_cause_class_for_every_gate():
    """The cause class is the deliverable; a gate without one cannot be attributed."""
    from src.research_infra.regime_spine.conditions import (
        AVAILABILITY,
        SLEEVES,
        STRUCTURE,
        THRESHOLD,
    )

    for name, cond in SLEEVES.items():
        assert cond.gates, name
        for g in cond.gates:
            assert g.cause in (AVAILABILITY, THRESHOLD, STRUCTURE), (name, g.name)
            if g.cause == THRESHOLD:
                assert g.stat, f"{name}/{g.name}: a threshold gate must name its statistic"
        for p in (p for g in cond.gates for p in g.params):
            assert p in cond.defaults, f"{name}: gate param {p!r} has no default"


def test_walk_reports_the_first_failing_gate_and_the_product_is_the_fire_rate():
    """The funnel identity is exact — `fires == slots * prod(conditional rates)`."""
    import datetime as _dt

    from src.research_infra.regime_spine import conditions as C
    from src.research_infra.regime_spine import ramp as R
    from src.research_infra.regime_spine.state import build_frame
    from tests.research_infra.test_regime_spine_state import _bars

    bars = _bars(1200, seed=11)
    t0 = _dt.datetime(2019, 1, 1, tzinfo=_dt.timezone.utc)
    times = [t0 + _dt.timedelta(hours=4 * i) for i in range(len(bars))]
    f = build_frame("XAUUSD", 16388, bars, times)
    cond = C.SLEEVES["metals_core"]
    fun = R.funnel_by_period({"XAUUSD": f}, cond, grain="year")
    for _period, counts in fun.items():
        prod = counts.slots
        for g in cond.gate_names():
            if not counts.reached[g]:
                prod = 0
                break
            prod *= counts.passed[g] / counts.reached[g]
        assert abs(prod - counts.fires) < 1e-9, "the funnel identity must be exact"
        # every non-firing bar is attributed to exactly one gate
        stopped = sum(counts.reached[g] - counts.passed[g] for g in cond.gate_names())
        assert stopped + counts.fires == counts.slots
